//! Shared helpers for the keelsign repository checks. Not published.
//!
//! The checks themselves live in `tests/`.
#![forbid(unsafe_code)]

use std::path::{Path, PathBuf};
use std::process::Command;

/// Crates that are published to crates.io as name-reservation placeholders.
pub const PLACEHOLDER_CRATES: [&str; 1] = ["keelsign"];

/// Published crates that carry their own copies of the root licence files.
pub const LICENSED_CRATES: [&str; 2] = ["keelsign", "keelsign-verify"];

/// A standalone embedded example project under `examples/`.
pub struct Example {
    /// Directory name under `examples/`, and the package name.
    pub name: &'static str,
    /// Rust target triple the example is built for.
    pub target: &'static str,
    /// probe-rs chip name passed to `probe-rs run --chip`.
    pub chip: &'static str,
    /// The HAL crate feature that selects the board's chip.
    pub hal_feature: &'static str,
}

/// The embedded examples, one per development board.
pub const EXAMPLES: [Example; 2] = [
    Example {
        name: "nrf52840-hello",
        target: "thumbv7em-none-eabihf",
        chip: "nRF52840_xxAA",
        hal_feature: "nrf52840",
    },
    Example {
        name: "rp2350-hello",
        target: "thumbv8m.main-none-eabihf",
        chip: "RP235x",
        hal_feature: "rp235xa",
    },
];

/// The standalone on-target benchmark projects under `benches/` (SHA-34), one per
/// development board. `name` is the directory under `benches/` and the package name.
pub const BENCHES: [Example; 2] = [
    Example {
        name: "nrf52840-mldsa",
        target: "thumbv7em-none-eabihf",
        chip: "nRF52840_xxAA",
        hal_feature: "nrf52840",
    },
    Example {
        name: "rp2350-mldsa",
        target: "thumbv8m.main-none-eabihf",
        chip: "RP235x",
        hal_feature: "rp235xa",
    },
];

/// Files the SHA-65 LMS/HSS additions put in every bench project, relative to its
/// directory.
pub const LMS_BENCH_FILES: [&str; 3] = [
    "tests/lms.rs",
    "src/bin/size_lms_baseline.rs",
    "src/bin/size_lms.rs",
];

/// The on-target LMS/HSS tests in `tests/lms.rs` named in the SHA-65 plan.
pub const LMS_ON_TARGET_TESTS: [&str; 3] = [
    "lms_kat",
    "lms_bench",
    "lms_rotation_key_b_verifies_against_a_b_and_fails_against_a",
];

/// The LMS/HSS flash-footprint bins (baseline first).
pub const LMS_SIZE_BINS: [&str; 2] = ["size_lms_baseline", "size_lms"];

/// Peak-stack limit for LMS/HSS verify asserted by `lms_bench` (SHA-65 AC4).
pub const LMS_STACK_LIMIT: u32 = 32_768;

/// Files the SHA-42 image-digest additions put in every bench project, relative to its
/// directory.
pub const DIGEST_BENCH_FILES: [&str; 3] = [
    "tests/image.rs",
    "src/bin/size_digest_baseline.rs",
    "src/bin/size_digest.rs",
];

/// The on-target image-digest tests in `tests/image.rs` named in the SHA-42 plan.
pub const DIGEST_ON_TARGET_TESTS: [&str; 2] =
    ["image_digest_200k_from_flash", "image_digest_bench"];

/// The image-digest flash-footprint bins (baseline first).
pub const DIGEST_SIZE_BINS: [&str; 2] = ["size_digest_baseline", "size_digest"];

/// Peak-stack limit for one 256-byte-chunk digest asserted by `image_digest_bench`
/// (SHA-42).
pub const DIGEST_STACK_LIMIT: u32 = 4096;

/// The SHA-37 sample images, the SHA-35 golden MCUboot images and the SHA-42 200 KB
/// image in `tests/fixtures/images/`, generated by `scripts/gen_image_fixtures.py`,
/// followed by the committed test-key files under `keys/` and the fixed classical
/// signatures under `sigs/`. Images under `rejected/` are ones the parser must reject.
/// Every entry is listed with its SHA-256 in `MANIFEST.json`.
pub const IMAGE_FIXTURES: [&str; 19] = [
    "keelsign-lms-m32-h5.bin",
    "keelsign-hss2-m32-h5h5.bin",
    "keelsign-lms-protected-tlvs.bin",
    "keelsign-hybrid-ed25519-lms.bin",
    "keelsign-mldsa44.bin",
    "keelsign-mldsa65.bin",
    "keelsign-dual-pq-invalid.bin",
    "mcuboot-rsa2048.bin",
    "mcuboot-ecdsa-p256.bin",
    "mcuboot-ed25519.bin",
    "mcuboot-ed25519-padded.bin",
    "rejected/mcuboot-ed25519-bigendian.bin",
    "mcuboot-ed25519-200k.bin",
    "keys/ed25519-test-key.pem",
    "keys/ed25519-test-key.spki.der",
    "keys/rsa2048-test-key.pem",
    "keys/ecdsa-p256-test-key.pem",
    "sigs/mcuboot-rsa2048.sig",
    "sigs/mcuboot-ecdsa-p256.sig",
];

/// Crates that ship (published or linked into user firmware). None of them may depend on
/// the measurement-only `stack-paint` crate.
pub const SHIPPED_CRATES: [&str; 4] = [
    "keelsign",
    "keelsign-verify",
    "keelsign-embassy",
    "keelsign-ffi",
];

/// Absolute path of the workspace root (two levels above this crate).
pub fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("workspace root must exist")
}

/// A per-test scratch directory under the system temp dir, unique per process
/// and test name. It is removed when dropped.
pub struct ScratchDir(PathBuf);

impl ScratchDir {
    pub fn new(test_name: &str) -> Self {
        let path = std::env::temp_dir().join(format!(
            "keelsign-repo-checks-{}-{}",
            std::process::id(),
            test_name
        ));
        let _ = std::fs::remove_dir_all(&path);
        std::fs::create_dir_all(&path).expect("create scratch dir");
        Self(path)
    }

    pub fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for ScratchDir {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

/// A `cargo` command run in `dir` with its own `CARGO_TARGET_DIR`, so it does not
/// contend for the build lock of the outer `cargo test`.
pub fn cargo_in(dir: &Path, target_dir: &Path) -> Command {
    let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
    let mut cmd = Command::new(cargo);
    cmd.current_dir(dir).env("CARGO_TARGET_DIR", target_dir);
    cmd
}

/// Run `cmd`, panicking with its output if it fails; returns stdout.
pub fn run_ok(cmd: &mut Command) -> String {
    let out = cmd.output().expect("spawn command");
    assert!(
        out.status.success(),
        "command {:?} failed with {}\nstdout:\n{}\nstderr:\n{}",
        cmd,
        out.status,
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    String::from_utf8(out.stdout).expect("stdout is UTF-8")
}

/// A `python3 <workspace>/scripts/<script>` command run from the workspace root.
pub fn python_script(script: &str) -> Command {
    let root = workspace_root();
    let mut cmd = Command::new("python3");
    cmd.current_dir(&root)
        .arg(root.join("scripts").join(script));
    cmd
}

/// Run `cmd` and return its exit success, stdout and stderr. Panics with a clear message
/// if the program cannot be started (for example `python3` missing from `PATH`).
pub fn run_capture(cmd: &mut Command) -> (bool, String, String) {
    let out = cmd.output().unwrap_or_else(|e| {
        panic!(
            "could not start {:?}: {e} (the SHA-34 scripts need `python3` on PATH)",
            cmd.get_program()
        )
    });
    (
        out.status.success(),
        String::from_utf8_lossy(&out.stdout).into_owned(),
        String::from_utf8_lossy(&out.stderr).into_owned(),
    )
}

/// Lowercase hex SHA-256 of `data` (FIPS 180-4), so the fixture checks need no extra
/// dependency.
pub fn sha256_hex(data: &[u8]) -> String {
    const K: [u32; 64] = [
        0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
        0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
        0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
        0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
        0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
        0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
        0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
        0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
        0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
        0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c, 0x1f83d9ab,
        0x5be0cd19,
    ];
    let mut msg = data.to_vec();
    msg.push(0x80);
    while msg.len() % 64 != 56 {
        msg.push(0);
    }
    msg.extend_from_slice(&((data.len() as u64) * 8).to_be_bytes());
    for block in msg.chunks_exact(64) {
        let mut w = [0u32; 64];
        for (i, word) in block.chunks_exact(4).enumerate() {
            w[i] = u32::from_be_bytes([word[0], word[1], word[2], word[3]]);
        }
        for i in 16..64 {
            let s0 = w[i - 15].rotate_right(7) ^ w[i - 15].rotate_right(18) ^ (w[i - 15] >> 3);
            let s1 = w[i - 2].rotate_right(17) ^ w[i - 2].rotate_right(19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16]
                .wrapping_add(s0)
                .wrapping_add(w[i - 7])
                .wrapping_add(s1);
        }
        let [mut a, mut b, mut c, mut d, mut e, mut f, mut g, mut hh] = h;
        for i in 0..64 {
            let s1 = e.rotate_right(6) ^ e.rotate_right(11) ^ e.rotate_right(25);
            let ch = (e & f) ^ (!e & g);
            let t1 = hh
                .wrapping_add(s1)
                .wrapping_add(ch)
                .wrapping_add(K[i])
                .wrapping_add(w[i]);
            let s0 = a.rotate_right(2) ^ a.rotate_right(13) ^ a.rotate_right(22);
            let maj = (a & b) ^ (a & c) ^ (b & c);
            let t2 = s0.wrapping_add(maj);
            hh = g;
            g = f;
            f = e;
            e = d.wrapping_add(t1);
            d = c;
            c = b;
            b = a;
            a = t1.wrapping_add(t2);
        }
        for (x, y) in h.iter_mut().zip([a, b, c, d, e, f, g, hh]) {
            *x = x.wrapping_add(y);
        }
    }
    h.iter().map(|x| format!("{x:08x}")).collect()
}
