//! On-target chunked image digest from flash on the Pico 2 W / RP2350 (SHA-42).
//!
//! Synchronous embedded-test cases, no embassy executor. Run from this directory with
//! `cargo test --release --locked --test image` (docs/benchmarks.md, "Image digest").
//!
//! The "DFU slot" is the 200 KB golden image `mcuboot-ed25519-200k.bin` embedded in this
//! test binary's `.rodata` with `include_bytes!`, read back through the HAL's
//! `ReadNorFlash` (the blocking `embassy_rp::flash::Flash`) at its flash offset with
//! `NorFlashReader`. Placing it at a
//! fixed partition address would need `#[link_section]`, which is an unsafe attribute in
//! edition 2024; the real DFU partition comes with the embassy-boot adapter (SHA-55).
#![no_std]
#![no_main]

// `not(clippy)`: `cargo clippy` checks the dev profile; the guard is for builds and runs.
#[cfg(all(debug_assertions, not(clippy)))]
compile_error!("run the on-target tests with `cargo test --release`");

use core::hint::black_box;
use cortex_m::peripheral::DWT;
use defmt::info;
use defmt_rtt as _;
use embassy_rp::flash::{Blocking, Flash};
use embassy_rp::peripherals::FLASH;
use keelsign_verify::image::{IMAGE_TLV_SHA256, Image};
use keelsign_verify::{Error, ImageReader, NorFlashReader, image_digest};
use mldsa_kat::measure::Cycles;
use stack_paint::Watermark;

/// Board name in the `DIGEST` log lines.
const BOARD: &str = "rp2350";
/// Core clock after `embassy_rp::init(Default::default())` (150 MHz).
const CPU_HZ: u32 = 150_000_000;
/// Bytes left unpainted below the stack pointer inside `stack_paint::paint`, covering
/// that function's own frame.
const PAINT_MARGIN: u32 = 256;
/// Peak-stack limit for one digest with a 256-byte chunk (SHA-42, docs/benchmarks.md).
const STACK_LIMIT: u32 = 4096;
/// The chunk size benchmarked: MCUboot's `BOOT_TMPBUF_SZ`.
const CHUNK: usize = keelsign_verify::DEFAULT_CHUNK_LEN;

/// External QSPI flash of the Pico 2 W: 4 MiB (the linker script uses only the first 2).
const FLASH_SIZE: usize = 4 * 1024 * 1024;
/// Where the XIP window maps the flash (`embassy_rp::flash::FLASH_BASE`).
const XIP_BASE: u32 = 0x1000_0000;

/// The blocking flash driver.
type Nvm = Flash<'static, FLASH, Blocking, FLASH_SIZE>;

/// The 200 KB golden image (generated by `scripts/gen_image_fixtures.py`), in flash.
static IMAGE: &[u8] = include_bytes!("../../../tests/fixtures/images/mcuboot-ed25519-200k.bin");

/// State handed from `#[init]` to the tests.
pub struct Board {
    dwt_present: bool,
    flash: Nvm,
}

fn init_board() -> Board {
    // Core peripherals first: embassy_rp::init does not take them.
    let dwt_present = match cortex_m::Peripherals::take() {
        Some(mut cp) => {
            cp.DCB.enable_trace();
            cp.DWT.enable_cycle_counter();
            DWT::has_cycle_counter()
        }
        None => false,
    };
    let p = embassy_rp::init(Default::default());
    Board {
        dwt_present,
        flash: Flash::new_blocking(p.FLASH),
    }
}

fn error_name(e: Error) -> &'static str {
    match e {
        Error::Parse(_) => "image does not parse",
        Error::Read(_) => "flash read failed",
        Error::TlvAreaTooLarge => "TLV areas larger than the TLV buffer",
        Error::ChunkBufferEmpty => "empty chunk buffer",
        _ => "unexpected error",
    }
}

/// The DFU slot: `IMAGE` read through the flash driver at its flash offset.
fn slot(flash: Nvm) -> Result<NorFlashReader<Nvm>, &'static str> {
    // The driver takes offsets from the start of the flash, not XIP addresses.
    let base = (IMAGE.as_ptr() as u32)
        .checked_sub(XIP_BASE)
        .ok_or("image is not in the XIP flash window")?;
    let len = u32::try_from(IMAGE.len()).map_err(|_| "image too large")?;
    NorFlashReader::new(flash, base, len).map_err(|_| "slot outside the flash")
}

/// The image's SHA256 TLV.
fn sha256_tlv<'a>(image: &Image<'a>) -> Result<&'a [u8], &'static str> {
    image
        .unprotected()
        .pairs()
        .find(|(t, _)| *t == IMAGE_TLV_SHA256)
        .map(|(_, v)| v)
        .ok_or("no SHA256 TLV")
}

fn digest_with<R: ImageReader>(
    reader: &mut R,
    image: &Image<'_>,
    chunk: &mut [u8],
) -> Result<[u8; 32], &'static str> {
    image_digest(reader, image, chunk).map_err(error_name)
}

/// `read_from` (4 KiB TLV buffer) and `image_digest` (256-byte chunk) from flash, checked
/// against the SHA256 TLV, the in-memory reader and the 64- and 4096-byte chunks.
fn digest_from_flash(flash: Nvm) -> Result<(), &'static str> {
    let mut reader = slot(flash)?;
    let mut tlv_buf = [0u8; 4096];
    let image = Image::read_from(&mut reader, &mut tlv_buf).map_err(error_name)?;
    let mut chunk = [0u8; CHUNK];
    let digest = digest_with(&mut reader, &image, &mut chunk)?;
    info!(
        "DIGEST_HEX board={=str} bytes={=u32} digest={=[u8]:02x}",
        BOARD,
        image.header().img_size,
        digest
    );
    if digest.as_slice() != sha256_tlv(&image)? {
        return Err("digest from flash differs from the SHA256 TLV");
    }
    let mut in_memory: &[u8] = IMAGE;
    if digest_with(&mut in_memory, &image, &mut chunk)? != digest {
        return Err("digest from flash differs from the in-memory reader's");
    }
    if digest_with(&mut reader, &image, &mut [0u8; 64])? != digest {
        return Err("64-byte chunks give a different digest");
    }
    if digest_with(&mut reader, &image, &mut [0u8; 4096])? != digest {
        return Err("4096-byte chunks give a different digest");
    }
    info!(
        "DIGEST board={=str} from_flash=ok sha256_tlv=ok chunks=64,256,4096 ok",
        BOARD
    );
    Ok(())
}

/// One digest with its 256-byte chunk on this frame, so that the chunk counts towards
/// the measured peak stack.
#[inline(never)]
fn digest_once<R: ImageReader>(reader: &mut R, image: &Image<'_>) -> Result<[u8; 32], Error> {
    let mut chunk = [0u8; CHUNK];
    image_digest(black_box(reader), black_box(image), black_box(&mut chunk))
}

/// Paints the stack, then times one digest and measures its stack high-water mark.
#[inline(never)]
fn measure<R: ImageReader>(
    reader: &mut R,
    image: &Image<'_>,
) -> (Result<[u8; 32], Error>, u32, Watermark) {
    let sp0 = cortex_m::register::msp::read();
    stack_paint::paint(PAINT_MARGIN);
    let timer = Cycles::start();
    let result = black_box(digest_once(reader, image));
    let cycles = timer.elapsed();
    (result, cycles, stack_paint::high_water(sp0))
}

fn bench(flash: Nvm) -> Result<(), &'static str> {
    let mut reader = slot(flash)?;
    let mut tlv_buf = [0u8; 4096];
    let image = Image::read_from(&mut reader, &mut tlv_buf).map_err(error_name)?;
    let (result, cycles, mark) = measure(&mut reader, &image);
    let digest = result.map_err(error_name)?;
    info!(
        "DIGEST board={=str} bytes={=u32} chunk={=usize} cycles={=u32} us={=u32} peak_stack={=u32} saturated={=bool}",
        BOARD,
        image.header().img_size,
        CHUNK,
        cycles,
        cycles / (CPU_HZ / 1_000_000),
        mark.bytes,
        mark.saturated
    );
    if digest.as_slice() != sha256_tlv(&image)? {
        return Err("digest differs from the SHA256 TLV");
    }
    if mark.saturated || mark.bytes > STACK_LIMIT {
        return Err("the digest saturated the painted stack or used more than 4 KB");
    }
    Ok(())
}

#[embedded_test::tests]
mod tests {
    use super::{Board, bench, digest_from_flash, init_board};

    #[init]
    fn init() -> Board {
        init_board()
    }

    #[test]
    fn image_digest_200k_from_flash(board: Board) -> Result<(), &'static str> {
        digest_from_flash(board.flash)
    }

    #[test]
    fn image_digest_bench(board: Board) -> Result<(), &'static str> {
        if !board.dwt_present {
            return Err("DWT has no cycle counter");
        }
        bench(board.flash)
    }
}
