/*
 * keelsign C ABI (libkeelsign.a). SPDX-License-Identifier: MIT OR Apache-2.0
 *
 * Generated by cbindgen 0.29.4 from keelsign-ffi/src with keelsign-ffi/cbindgen.toml.
 * DO NOT EDIT: regenerate with
 *   cbindgen --config keelsign-ffi/cbindgen.toml --crate keelsign-ffi --output keelsign-ffi/include/keelsign.h keelsign-ffi
 *
 * Build the library from the repository root:
 *   cargo build -p keelsign-ffi --profile ffi --locked [--target <triple>] [--features ed25519,ml-dsa]
 * which writes target[/<triple>]/ffi/libkeelsign.a. Always use --profile ffi: a host
 * --release or dev build of keelsign-ffi links std and unwinds on panic, so it is not
 * the shipped library. Pointer and length contract: see each function below and
 * docs/ffi.md.
 */

#ifndef KEELSIGN_H
#define KEELSIGN_H

#include <stdint.h>
#include <stddef.h>

// Version of this C ABI. Bumped on any incompatible change to the header.
#define KEELSIGN_ABI_VERSION 1

// The most post-quantum keys (`KEELSIGN_ALG_MLDSA44`, `KEELSIGN_ALG_MLDSA65`,
// `KEELSIGN_ALG_LMS_HSS`) one `keelsign_verify` call accepts.
#define KEELSIGN_MAX_PQ_KEYS 8

// The most Ed25519 keys (`KEELSIGN_ALG_ED25519`) one `keelsign_verify` call accepts.
#define KEELSIGN_MAX_ED25519_KEYS 8

// Bytes of the stack buffer the TLV areas are copied into. Images whose TLV areas need
// more fail with `KEELSIGN_ERR_TLV_AREA_TOO_LARGE`. Fits one ML-DSA-65 signature and the
// usual MCUboot TLVs.
#define KEELSIGN_TLV_BUF_LEN 4096

// Bytes of the stack buffer the image body is hashed through
// (`keelsign_verify::DEFAULT_CHUNK_LEN`).
#define KEELSIGN_CHUNK_LEN 256

// `keelsign_result_t.pq_key_index` / `ed25519_key_index` when no key of that kind
// verified the image.
#define KEELSIGN_NO_KEY 4294967295

// The result of a keelsign call. `KEELSIGN_OK` (0) is success; every other value is an
// error. The numbers are stable: a code is never renumbered or reused. Treat any value
// you do not recognise as an error.
//
// | Range | Group |
// |---|---|
// | 1–4 | arguments |
// | 5–9 | the trusted key set |
// | 10–23 | the post-quantum half and buffers |
// | 30–39 | image parsing |
// | 40–49 | reading the image |
// | 50–59 | the Ed25519 half |
// | 60–79 | image rules |
// | 99 | an error this ABI version does not know |
enum keelsign_status_t
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // Success.
  KEELSIGN_OK = 0,
  // A pointer argument that must not be NULL is NULL.
  KEELSIGN_ERR_NULL_POINTER = 1,
  // `len` is above `UINT32_MAX` (or, on a 32-bit target, above `PTRDIFF_MAX`).
  KEELSIGN_ERR_IMAGE_TOO_LARGE = 2,
  // `policy` is not a `KEELSIGN_POLICY_*` value.
  KEELSIGN_ERR_INVALID_POLICY = 3,
  // A key's `alg` is not a `KEELSIGN_ALG_*` value.
  KEELSIGN_ERR_INVALID_ALGORITHM = 4,
  // More than `KEELSIGN_MAX_PQ_KEYS` post-quantum or `KEELSIGN_MAX_ED25519_KEYS`
  // Ed25519 keys.
  KEELSIGN_ERR_TOO_MANY_KEYS = 5,
  // Two keys have the same key ID (post-quantum) or KEYHASH (Ed25519).
  KEELSIGN_ERR_DUPLICATE_KEY = 6,
  // A key has the wrong length for its algorithm (or is not a valid LMS/HSS key).
  KEELSIGN_ERR_KEY_LENGTH = 7,
  // The key set was rejected for a reason this ABI version does not know.
  KEELSIGN_ERR_KEYSET_UNKNOWN = 9,
  // No post-quantum key-ID TLV.
  KEELSIGN_ERR_MISSING_KEY_ID = 10,
  // The post-quantum key-ID TLV has the wrong length.
  KEELSIGN_ERR_INVALID_KEY_ID = 11,
  // More than one post-quantum key-ID TLV.
  KEELSIGN_ERR_MULTIPLE_KEY_IDS = 12,
  // No post-quantum signature TLV.
  KEELSIGN_ERR_MISSING_PQ_SIGNATURE = 13,
  // More than one post-quantum signature TLV.
  KEELSIGN_ERR_MULTIPLE_PQ_SIGNATURES = 14,
  // The image's post-quantum key ID is not among the trusted keys.
  KEELSIGN_ERR_KEY_NOT_TRUSTED = 15,
  // The trusted key's algorithm does not match the signature TLV.
  KEELSIGN_ERR_KEY_ALGORITHM_MISMATCH = 16,
  // The image is signed with an algorithm this build does not verify (ML-DSA without
  // the `ml-dsa` feature).
  KEELSIGN_ERR_UNSUPPORTED_ALGORITHM = 17,
  // Unsupported post-quantum parameter set.
  KEELSIGN_ERR_UNSUPPORTED_PARAMETER_SET = 18,
  // The post-quantum signature is malformed.
  KEELSIGN_ERR_MALFORMED_SIGNATURE = 19,
  // The trusted post-quantum public key is malformed.
  KEELSIGN_ERR_INVALID_PUBLIC_KEY = 20,
  // The post-quantum signature does not verify.
  KEELSIGN_ERR_SIGNATURE_INVALID = 21,
  // The TLV areas do not fit `KEELSIGN_TLV_BUF_LEN`.
  KEELSIGN_ERR_TLV_AREA_TOO_LARGE = 22,
  // The digest chunk buffer is empty (never returned by this library).
  KEELSIGN_ERR_CHUNK_BUFFER_EMPTY = 23,
  // Not a little-endian MCUboot image (bad header magic).
  KEELSIGN_ERR_PARSE_BAD_MAGIC = 30,
  // The image is truncated (also: `len` is 0).
  KEELSIGN_ERR_PARSE_TRUNCATED = 31,
  // The header size is below 32 bytes.
  KEELSIGN_ERR_PARSE_HEADER_TOO_SMALL = 32,
  // The image sizes overflow.
  KEELSIGN_ERR_PARSE_SIZE_OVERFLOW = 33,
  // A TLV info header has the wrong magic.
  KEELSIGN_ERR_PARSE_BAD_TLV_INFO_MAGIC = 34,
  // The protected TLV area size does not match the header.
  KEELSIGN_ERR_PARSE_PROTECTED_SIZE_MISMATCH = 35,
  // A TLV length runs past its area.
  KEELSIGN_ERR_PARSE_LENGTH_MISMATCH = 36,
  // The post-quantum signature TLV is too long.
  KEELSIGN_ERR_PARSE_PQ_SIGNATURE_TOO_LONG = 37,
  // The image does not parse, for a reason this ABI version does not know.
  KEELSIGN_ERR_PARSE_UNKNOWN = 39,
  // A read ran past the end of the image.
  KEELSIGN_ERR_READ_OUT_OF_BOUNDS = 40,
  // A read was not aligned.
  KEELSIGN_ERR_READ_NOT_ALIGNED = 41,
  // Another read error.
  KEELSIGN_ERR_READ_OTHER = 42,
  // A read error this ABI version does not know.
  KEELSIGN_ERR_READ_UNKNOWN = 49,
  // The policy needs the Ed25519 half and the library was built without `ed25519`.
  KEELSIGN_ERR_ED25519_NOT_ENABLED = 50,
  // No ED25519 signature TLV.
  KEELSIGN_ERR_ED25519_MISSING = 51,
  // More than one ED25519 or KEYHASH TLV.
  KEELSIGN_ERR_ED25519_MULTIPLE = 52,
  // The ED25519 TLV does not follow a KEYHASH TLV.
  KEELSIGN_ERR_ED25519_UNPAIRED = 53,
  // The KEYHASH TLV has the wrong length.
  KEELSIGN_ERR_ED25519_INVALID_KEYHASH = 54,
  // The ED25519 TLV has the wrong length.
  KEELSIGN_ERR_ED25519_INVALID_SIGNATURE_LENGTH = 55,
  // The KEYHASH is not among the trusted Ed25519 keys.
  KEELSIGN_ERR_ED25519_KEY_NOT_TRUSTED = 56,
  // The trusted Ed25519 public key is malformed.
  KEELSIGN_ERR_ED25519_INVALID_PUBLIC_KEY = 57,
  // The Ed25519 signature does not verify.
  KEELSIGN_ERR_ED25519_SIGNATURE_INVALID = 58,
  // The Ed25519 half failed for a reason this ABI version does not know.
  KEELSIGN_ERR_ED25519_UNKNOWN = 59,
  // Encrypted images are not supported.
  KEELSIGN_ERR_IMAGE_ENCRYPTED = 60,
  // Compressed images are not supported.
  KEELSIGN_ERR_IMAGE_COMPRESSED = 61,
  // The image is flagged non-bootable.
  KEELSIGN_ERR_IMAGE_NON_BOOTABLE = 62,
  // A keelsign TLV is in the protected TLV area.
  KEELSIGN_ERR_IMAGE_KEELSIGN_TLV_PROTECTED = 63,
  // SIG_PURE images are not supported.
  KEELSIGN_ERR_IMAGE_SIG_PURE = 64,
  // No SHA256 TLV.
  KEELSIGN_ERR_IMAGE_MISSING_SHA256_TLV = 65,
  // More than one SHA256 TLV.
  KEELSIGN_ERR_IMAGE_MULTIPLE_SHA256_TLVS = 66,
  // The SHA256 TLV has the wrong length.
  KEELSIGN_ERR_IMAGE_INVALID_SHA256_TLV = 67,
  // More than one protected security counter TLV.
  KEELSIGN_ERR_IMAGE_MULTIPLE_SECURITY_COUNTERS = 68,
  // The protected security counter TLV has the wrong length.
  KEELSIGN_ERR_IMAGE_INVALID_SECURITY_COUNTER = 69,
  // The SHA256 TLV does not match the image digest.
  KEELSIGN_ERR_IMAGE_DIGEST_MISMATCH = 70,
  // An image rule this ABI version does not know was broken.
  KEELSIGN_ERR_IMAGE_UNKNOWN = 79,
  // An error this ABI version does not know.
  KEELSIGN_ERR_UNKNOWN = 99,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum keelsign_status_t keelsign_status_t;
#else
typedef int32_t keelsign_status_t;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A key algorithm (`KEELSIGN_ALG_*`).
typedef uint32_t keelsign_alg_t;

// One trusted public key. `key` must point to `key_len` readable bytes for the duration
// of the call; nothing is retained after it returns.
typedef struct keelsign_key_t {
  // The key's algorithm.
  keelsign_alg_t alg;
  // The raw encoded public key (never NULL).
  const uint8_t *key;
  // Bytes at `key`.
  size_t key_len;
} keelsign_key_t;

// A verification policy (`KEELSIGN_POLICY_*`).
typedef uint32_t keelsign_policy_t;

// What `keelsign_verify` reports about an image it accepted.
typedef struct keelsign_result_t {
  // `ih_ver.iv_major`.
  uint8_t major;
  // `ih_ver.iv_minor`.
  uint8_t minor;
  // `ih_ver.iv_revision`.
  uint16_t revision;
  // `ih_ver.iv_build_num`.
  uint32_t build_num;
  // 1 if the protected TLV area holds a security counter, else 0.
  uint8_t has_security_counter;
  // The security counter (0 when `has_security_counter` is 0).
  uint32_t security_counter;
  // Bytes from the start of the image to the end of its TLV areas.
  uint32_t image_len;
  // The image digest `M` (SHA-256 of header, body and protected TLVs).
  uint8_t digest[32];
  // Index into the caller's `keys` array of the post-quantum key that verified the
  // image, or `KEELSIGN_NO_KEY` (ClassicalOnly).
  uint32_t pq_key_index;
  // Index into the caller's `keys` array of the Ed25519 key that verified the image,
  // or `KEELSIGN_NO_KEY` (PqOnly).
  uint32_t ed25519_key_index;
} keelsign_result_t;

// An image that `keelsign_verify_cb` reads through a callback instead of a pointer: an
// image slot in flash that is not memory-mapped (MCUboot's `flash_area_read`).
//
// keelsign calls `read` only for ranges inside `[0, len)`: the header, the TLV areas,
// then the hashed bytes after the header in ascending `KEELSIGN_CHUNK_LEN`-byte chunks,
// at any offset and length (no alignment), with `buf` pointing to keelsign's own stack
// buffers. Nothing is retained after the call.
typedef struct keelsign_reader_t {
  // Passed unchanged to every `read` call.
  void *ctx;
  // Readable bytes from offset 0: the slot size (or the slot minus its trailer).
  uint32_t len;
  // Reads `len` bytes at image-relative `offset` into `buf` (never NULL). Returns 0
  // when all `len` bytes were read; any other value fails the call with
  // `KEELSIGN_ERR_READ_OTHER`.
  int32_t (*read)(void *ctx, uint32_t offset, uint8_t *buf, size_t len);
} keelsign_reader_t;

// ML-DSA-44 (FIPS 204); a raw 1312-byte public key. Needs the `ml-dsa` feature to verify.
#define KEELSIGN_ALG_MLDSA44 1

// ML-DSA-65 (FIPS 204); a raw 1952-byte public key. Needs the `ml-dsa` feature to verify.
#define KEELSIGN_ALG_MLDSA65 2

// LMS/HSS (RFC 8554, SP 800-208); a raw 52-byte (HSS L=1) or 60-byte public key.
#define KEELSIGN_ALG_LMS_HSS 3

// Ed25519; the raw 32-byte public key. Needs the `ed25519` feature to verify.
#define KEELSIGN_ALG_ED25519 4

// The Ed25519 half only (MCUboot's KEYHASH + ED25519 pair). Needs the `ed25519` feature;
// without it the call fails with `KEELSIGN_ERR_ED25519_NOT_ENABLED`.
#define KEELSIGN_POLICY_CLASSICAL_ONLY 1

// The post-quantum half only (keelsign key ID + one PQ signature TLV).
#define KEELSIGN_POLICY_PQ_ONLY 2

// Both halves over the same digest. Needs the `ed25519` feature; without it the call
// fails with `KEELSIGN_ERR_ED25519_NOT_ENABLED`.
#define KEELSIGN_POLICY_HYBRID 3

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Verify the MCUboot image `image[0..len)` under `policy` with the trusted `keys`.
//
// Returns `KEELSIGN_OK` and, if `out` is not NULL, writes what was verified to `*out`.
// On any error `*out` is left untouched.
//
// Arguments are checked in this order, the first failure is returned:
// `image` NULL or `keys` NULL with `n_keys > 0` (`KEELSIGN_ERR_NULL_POINTER`);
// `len > UINT32_MAX` (`KEELSIGN_ERR_IMAGE_TOO_LARGE`); `policy`
// (`KEELSIGN_ERR_INVALID_POLICY`); then each key in array order: its `alg`
// (`KEELSIGN_ERR_INVALID_ALGORITHM`), its `key` pointer (`KEELSIGN_ERR_NULL_POINTER`),
// the per-kind limit `KEELSIGN_MAX_PQ_KEYS` / `KEELSIGN_MAX_ED25519_KEYS`
// (`KEELSIGN_ERR_TOO_MANY_KEYS`) and its length (`KEELSIGN_ERR_KEY_LENGTH`); then the
// key set as a whole (duplicates, LMS/HSS key format); then the image. `len == 0` gives
// `KEELSIGN_ERR_PARSE_TRUNCATED`.
//
// `pq_key_index` / `ed25519_key_index` in `*out` are indices into `keys`, found by
// pointer identity, so they name the caller's slot whatever the key order.
//
// # Safety
//
// - `image` is non-NULL and readable for `len` bytes, at any alignment. A `len` above
//   `UINT32_MAX`, or on a 32-bit target above `PTRDIFF_MAX`, is rejected with
//   `KEELSIGN_ERR_IMAGE_TOO_LARGE` before anything is read.
// - `keys` is NULL only if `n_keys` is 0; otherwise it points to `n_keys` consecutive
//   `keelsign_key_t` (any alignment).
// - Each `keys[i].key` is non-NULL and readable for `keys[i].key_len` bytes.
// - `out` is NULL or writable for one `keelsign_result_t` (any alignment), and does
//   not overlap `image`, `keys` or any key's bytes.
// - None of this memory is written by anyone else during the call. Nothing is retained
//   after the call returns.
keelsign_status_t keelsign_verify(const uint8_t *image,
                                  size_t len,
                                  const struct keelsign_key_t *keys,
                                  size_t n_keys,
                                  keelsign_policy_t policy,
                                  struct keelsign_result_t *out);

// Verify the MCUboot image that `reader` reads, under `policy` with the trusted `keys`:
// `keelsign_verify` for an image that is not in addressable memory (an MCUboot slot
// read with `flash_area_read`). Same keys, policy, result and status codes.
//
// `reader->read` is called only for ranges inside `[0, reader->len)`, at most
// `KEELSIGN_TLV_BUF_LEN` bytes at a time: the header, the TLV areas, then the hashed
// bytes after the header in ascending `KEELSIGN_CHUNK_LEN`-byte chunks. A non-zero
// return fails the call with `KEELSIGN_ERR_READ_OTHER`.
//
// Arguments are checked in this order, the first failure is returned:
// `reader` NULL, `reader->read` NULL or `keys` NULL with `n_keys > 0`
// (`KEELSIGN_ERR_NULL_POINTER`); then as `keelsign_verify` from `policy` on.
// `reader->len == 0` gives `KEELSIGN_ERR_PARSE_TRUNCATED` without calling `read`.
//
// # Safety
//
// - `reader` is non-NULL and points to one readable `keelsign_reader_t` (any
//   alignment), which is copied before the first `read` call.
// - `reader->read`, if not NULL, is a function that is safe to call with `reader->ctx`,
//   an `offset` and `len` inside `[0, reader->len)` and a `buf` writable for `len`
//   bytes; it writes nothing but `buf[0..len)` and the state behind `ctx` (never `out`,
//   `keys` or any key's bytes).
// - `keys` is NULL only if `n_keys` is 0; otherwise it points to `n_keys` consecutive
//   `keelsign_key_t` (any alignment).
// - Each `keys[i].key` is non-NULL and readable for `keys[i].key_len` bytes.
// - `out` is NULL or writable for one `keelsign_result_t` (any alignment), and does
//   not overlap `keys` or any key's bytes.
// - None of this memory is written by anyone else during the call. Nothing is retained
//   after the call returns.
keelsign_status_t keelsign_verify_cb(const struct keelsign_reader_t *reader,
                                     const struct keelsign_key_t *keys,
                                     size_t n_keys,
                                     keelsign_policy_t policy,
                                     struct keelsign_result_t *out);

// Compute the image digest `M` of `image[0..len)` (SHA-256 of the header, the body and
// the protected TLV area, as both signatures cover it) and write its 32 bytes to
// `out_digest`. The image is parsed but no signature is checked.
//
// Returns `KEELSIGN_ERR_NULL_POINTER` if either pointer is NULL,
// `KEELSIGN_ERR_IMAGE_TOO_LARGE` if `len > UINT32_MAX`, else a parse or read error or
// `KEELSIGN_OK`. `out_digest` is written only on `KEELSIGN_OK`.
//
// # Safety
//
// - `image` is non-NULL and readable for `len` bytes, at any alignment. A `len` above
//   `UINT32_MAX`, or on a 32-bit target above `PTRDIFF_MAX`, is rejected with
//   `KEELSIGN_ERR_IMAGE_TOO_LARGE` before anything is read.
// - `out_digest` is non-NULL and writable for 32 bytes, and does not overlap `image`.
// - None of this memory is written by anyone else during the call. Nothing is retained
//   after the call returns.
keelsign_status_t keelsign_digest(const uint8_t *image, size_t len, uint8_t *out_digest);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* KEELSIGN_H */
