//! The SHA-46 policy matrix as a runnable index, for the host test and the on-target
//! `tests/policy.rs` of both bench projects.
//!
//! `tests/fixtures/images/policy-matrix.bin` is written by `scripts/gen_image_fixtures.py`
//! from the `policy` (and `policy_without_ml_dsa`, SHA-44) cells of `MANIFEST.json`. This
//! crate parses it without allocation or panics, finds each case's image (embedded once
//! with `include_bytes!` in [`IMAGES`]), and runs [`keelsign_verify::verify_with`] on it
//! under every [`Policy`], with the case's post-quantum key and the Ed25519 test key
//! trusted, so the same code checks the matrix on the host and on the boards.
//!
//! Index format "KSPM v2" (lengths little-endian):
//!
//! ```text
//! header:   b"KSPM", u16 version (2), u16 case count
//! per case: u8 name_len, name (UTF-8, the MANIFEST.json name),
//!           u8 pq_alg (0 none, 1 MlDsa44, 2 MlDsa65, 3 LmsHss), u16 pk_len, pk,
//!           u8 expect_classical_only, u8 expect_pq_only, u8 expect_hybrid
//!             (with the `ml-dsa` feature),
//!           u8 expect_classical_only, u8 expect_pq_only, u8 expect_hybrid
//!             (without it)
//! expectation codes: the index of the verdict in `Expect::ALL` (the script's
//!                    POLICY_CODES)
//! ```
//!
//! [`run_case`] picks the set by [`Algorithm::is_enabled`] at run time, so Cargo feature
//! unification cannot make it pick the wrong one.
#![no_std]
#![forbid(unsafe_code)]

pub use keelsign_verify::{Error, Policy};

use keelsign_verify::{
    Algorithm, Backend, Ed25519Error, Ed25519Key, ImageError, ImageReader, KeySetError, TrustedKey,
    TrustedKeys, VerifiedImage, verify_with,
};

/// Index magic bytes.
pub const MAGIC: [u8; 4] = *b"KSPM";

/// Index format version.
pub const VERSION: u16 = 2;

/// The on-target index: every image of the matrix but the 200 KB one.
pub const POLICY_TARGET: &[u8] = include_bytes!("../../../tests/fixtures/images/policy-matrix.bin");

/// Cases in [`POLICY_TARGET`].
pub const TARGET_CASES: u32 = 57;

/// The Ed25519 test key (`keys/ed25519-test-key.spki.der` without its 12-byte RFC 8410
/// prefix), trusted for every case.
pub static ED25519_TEST_KEY: [u8; 32] = ed25519_test_key();

const SPKI: &[u8] = include_bytes!("../../../tests/fixtures/images/keys/ed25519-test-key.spki.der");

const fn ed25519_test_key() -> [u8; 32] {
    // The SubjectPublicKeyInfo is 44 bytes, the raw key its last 32 (the host test checks
    // both).
    match SPKI.split_last_chunk::<32>() {
        Some((_, key)) => *key,
        None => [0; 32],
    }
}

macro_rules! image {
    ($name:literal) => {
        (
            $name,
            include_bytes!(concat!("../../../tests/fixtures/images/", $name)).as_slice(),
        )
    };
}

/// Every image [`POLICY_TARGET`] names, by its MANIFEST.json name (generated by
/// `scripts/gen_image_fixtures.py`).
pub static IMAGES: [(&str, &[u8]); 57] = [
    image!("keelsign-dual-pq-invalid.bin"),
    image!("keelsign-hss2-m32-h5h5.bin"),
    image!("keelsign-hybrid-bad-body.bin"),
    image!("keelsign-hybrid-bad-ed25519.bin"),
    image!("keelsign-hybrid-bad-pq.bin"),
    image!("keelsign-hybrid-bad-sha256.bin"),
    image!("keelsign-hybrid-ed25519-hss2.bin"),
    image!("keelsign-hybrid-ed25519-lms.bin"),
    image!("keelsign-hybrid-ed25519-mldsa44.bin"),
    image!("keelsign-hybrid-flag-compressed.bin"),
    image!("keelsign-hybrid-flag-encrypted.bin"),
    image!("keelsign-hybrid-flag-non-bootable.bin"),
    image!("keelsign-hybrid-hss2-bad-ed25519.bin"),
    image!("keelsign-hybrid-hss2-bad-pq.bin"),
    image!("keelsign-hybrid-hss2-bad-top-level.bin"),
    image!("keelsign-hybrid-hss2-missing-pq.bin"),
    image!("keelsign-hybrid-keyhash-only.bin"),
    image!("keelsign-hybrid-missing-key-id.bin"),
    image!("keelsign-hybrid-missing-pq.bin"),
    image!("keelsign-hybrid-mldsa44-missing-pq.bin"),
    image!("keelsign-hybrid-mldsa44-stripped-pq.bin"),
    image!("keelsign-hybrid-no-sha256.bin"),
    image!("keelsign-hybrid-protected-tlvs.bin"),
    image!("keelsign-hybrid-reserved-tlv-protected.bin"),
    image!("keelsign-hybrid-sha384-only.bin"),
    image!("keelsign-hybrid-short-ed25519.bin"),
    image!("keelsign-hybrid-sig-pure.bin"),
    image!("keelsign-hybrid-two-ed25519.bin"),
    image!("keelsign-hybrid-two-sec-cnt.bin"),
    image!("keelsign-hybrid-two-sha256.bin"),
    image!("keelsign-hybrid-unpaired-ed25519.bin"),
    image!("keelsign-lms-m32-h5.bin"),
    image!("keelsign-lms-protected-tlvs.bin"),
    image!("keelsign-mldsa44-bad-body-rehashed.bin"),
    image!("keelsign-mldsa44-bad-body.bin"),
    image!("keelsign-mldsa44-bad-hint.bin"),
    image!("keelsign-mldsa44-bad-key-id.bin"),
    image!("keelsign-mldsa44-bad-protected-rehashed.bin"),
    image!("keelsign-mldsa44-bad-protected.bin"),
    image!("keelsign-mldsa44-bad-sig.bin"),
    image!("keelsign-mldsa44-foreign-sig.bin"),
    image!("keelsign-mldsa44-protected-tlvs.bin"),
    image!("keelsign-mldsa44-short-sig.bin"),
    image!("keelsign-mldsa44.bin"),
    image!("keelsign-mldsa65-bad-body-rehashed.bin"),
    image!("keelsign-mldsa65-bad-hint.bin"),
    image!("keelsign-mldsa65-bad-protected-rehashed.bin"),
    image!("keelsign-mldsa65-bad-sig.bin"),
    image!("keelsign-mldsa65-foreign-sig.bin"),
    image!("keelsign-mldsa65-protected-tlvs.bin"),
    image!("keelsign-mldsa65-short-sig.bin"),
    image!("keelsign-mldsa65.bin"),
    image!("mcuboot-ecdsa-p256.bin"),
    image!("mcuboot-ed25519-padded.bin"),
    image!("mcuboot-ed25519.bin"),
    image!("mcuboot-rsa2048.bin"),
    image!("rejected/mcuboot-ed25519-bigendian.bin"),
];

/// The image named `name` in [`IMAGES`].
pub fn image(name: &str) -> Option<&'static [u8]> {
    IMAGES
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, data)| *data)
}

/// The expected verdict of one cell: the verdict strings of the script's `POLICY_CODES`,
/// in code order.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Expect {
    /// `Ok`.
    Ok,
    /// `Parse(BadMagic)`.
    ParseBadMagic,
    /// `MissingPqSignature`.
    MissingPqSignature,
    /// `MissingKeyId`.
    MissingKeyId,
    /// `MultiplePqSignatures`.
    MultiplePqSignatures,
    /// `SignatureInvalid`.
    SignatureInvalid,
    /// `UnsupportedAlgorithm(MlDsa44)`.
    UnsupportedMlDsa44,
    /// `UnsupportedAlgorithm(MlDsa65)`.
    UnsupportedMlDsa65,
    /// `Ed25519(Missing)`.
    Ed25519Missing,
    /// `Ed25519(Multiple)`.
    Ed25519Multiple,
    /// `Ed25519(Unpaired)`.
    Ed25519Unpaired,
    /// `Ed25519(InvalidSignatureLength)`.
    Ed25519InvalidSignatureLength,
    /// `Ed25519(SignatureInvalid)`.
    Ed25519SignatureInvalid,
    /// `Image(Encrypted)`.
    ImageEncrypted,
    /// `Image(Compressed)`.
    ImageCompressed,
    /// `Image(NonBootable)`.
    ImageNonBootable,
    /// `Image(KeelsignTlvProtected(0x4BA0))`.
    ImageKeelsignTlvProtectedKeyId,
    /// `Image(SigPure)`.
    ImageSigPure,
    /// `Image(MissingSha256Tlv)`.
    ImageMissingSha256Tlv,
    /// `Image(MultipleSha256Tlvs)`.
    ImageMultipleSha256Tlvs,
    /// `Image(MultipleSecurityCounters)`.
    ImageMultipleSecurityCounters,
    /// `Image(DigestMismatch)`.
    ImageDigestMismatch,
    /// `MalformedSignature` (SHA-44).
    MalformedSignature,
    /// `KeyNotTrusted` (SHA-44).
    KeyNotTrusted,
}

impl Expect {
    /// Every expectation, in code order.
    pub const ALL: [Expect; 24] = [
        Expect::Ok,
        Expect::ParseBadMagic,
        Expect::MissingPqSignature,
        Expect::MissingKeyId,
        Expect::MultiplePqSignatures,
        Expect::SignatureInvalid,
        Expect::UnsupportedMlDsa44,
        Expect::UnsupportedMlDsa65,
        Expect::Ed25519Missing,
        Expect::Ed25519Multiple,
        Expect::Ed25519Unpaired,
        Expect::Ed25519InvalidSignatureLength,
        Expect::Ed25519SignatureInvalid,
        Expect::ImageEncrypted,
        Expect::ImageCompressed,
        Expect::ImageNonBootable,
        Expect::ImageKeelsignTlvProtectedKeyId,
        Expect::ImageSigPure,
        Expect::ImageMissingSha256Tlv,
        Expect::ImageMultipleSha256Tlvs,
        Expect::ImageMultipleSecurityCounters,
        Expect::ImageDigestMismatch,
        Expect::MalformedSignature,
        Expect::KeyNotTrusted,
    ];

    /// The expectation with index code `code`.
    pub fn from_code(code: u8) -> Option<Self> {
        Self::ALL.get(usize::from(code)).copied()
    }

    /// The verdict string, as in MANIFEST.json and docs/policy.md.
    pub const fn name(self) -> &'static str {
        match self {
            Expect::Ok => "Ok",
            Expect::ParseBadMagic => "Parse(BadMagic)",
            Expect::MissingPqSignature => "MissingPqSignature",
            Expect::MissingKeyId => "MissingKeyId",
            Expect::MultiplePqSignatures => "MultiplePqSignatures",
            Expect::SignatureInvalid => "SignatureInvalid",
            Expect::UnsupportedMlDsa44 => "UnsupportedAlgorithm(MlDsa44)",
            Expect::UnsupportedMlDsa65 => "UnsupportedAlgorithm(MlDsa65)",
            Expect::Ed25519Missing => "Ed25519(Missing)",
            Expect::Ed25519Multiple => "Ed25519(Multiple)",
            Expect::Ed25519Unpaired => "Ed25519(Unpaired)",
            Expect::Ed25519InvalidSignatureLength => "Ed25519(InvalidSignatureLength)",
            Expect::Ed25519SignatureInvalid => "Ed25519(SignatureInvalid)",
            Expect::ImageEncrypted => "Image(Encrypted)",
            Expect::ImageCompressed => "Image(Compressed)",
            Expect::ImageNonBootable => "Image(NonBootable)",
            Expect::ImageKeelsignTlvProtectedKeyId => "Image(KeelsignTlvProtected(0x4BA0))",
            Expect::ImageSigPure => "Image(SigPure)",
            Expect::ImageMissingSha256Tlv => "Image(MissingSha256Tlv)",
            Expect::ImageMultipleSha256Tlvs => "Image(MultipleSha256Tlvs)",
            Expect::ImageMultipleSecurityCounters => "Image(MultipleSecurityCounters)",
            Expect::ImageDigestMismatch => "Image(DigestMismatch)",
            Expect::MalformedSignature => "MalformedSignature",
            Expect::KeyNotTrusted => "KeyNotTrusted",
        }
    }

    /// The expectation a verification result stands for, if it is one of the matrix's.
    pub fn of(result: &Result<VerifiedImage<'_>, Error>) -> Option<Self> {
        use keelsign_verify::image::ParseError;
        let err = match result {
            Ok(_) => return Some(Expect::Ok),
            Err(e) => *e,
        };
        Some(match err {
            Error::Parse(ParseError::BadMagic) => Expect::ParseBadMagic,
            Error::MissingPqSignature => Expect::MissingPqSignature,
            Error::MissingKeyId => Expect::MissingKeyId,
            Error::MultiplePqSignatures => Expect::MultiplePqSignatures,
            Error::SignatureInvalid => Expect::SignatureInvalid,
            Error::UnsupportedAlgorithm(Algorithm::MlDsa44) => Expect::UnsupportedMlDsa44,
            Error::UnsupportedAlgorithm(Algorithm::MlDsa65) => Expect::UnsupportedMlDsa65,
            Error::Ed25519(Ed25519Error::Missing) => Expect::Ed25519Missing,
            Error::Ed25519(Ed25519Error::Multiple) => Expect::Ed25519Multiple,
            Error::Ed25519(Ed25519Error::Unpaired) => Expect::Ed25519Unpaired,
            Error::Ed25519(Ed25519Error::InvalidSignatureLength) => {
                Expect::Ed25519InvalidSignatureLength
            }
            Error::Ed25519(Ed25519Error::SignatureInvalid) => Expect::Ed25519SignatureInvalid,
            Error::Image(ImageError::Encrypted) => Expect::ImageEncrypted,
            Error::Image(ImageError::Compressed) => Expect::ImageCompressed,
            Error::Image(ImageError::NonBootable) => Expect::ImageNonBootable,
            Error::Image(ImageError::KeelsignTlvProtected(0x4BA0)) => {
                Expect::ImageKeelsignTlvProtectedKeyId
            }
            Error::Image(ImageError::SigPure) => Expect::ImageSigPure,
            Error::Image(ImageError::MissingSha256Tlv) => Expect::ImageMissingSha256Tlv,
            Error::Image(ImageError::MultipleSha256Tlvs) => Expect::ImageMultipleSha256Tlvs,
            Error::Image(ImageError::MultipleSecurityCounters) => {
                Expect::ImageMultipleSecurityCounters
            }
            Error::Image(ImageError::DigestMismatch) => Expect::ImageDigestMismatch,
            Error::MalformedSignature => Expect::MalformedSignature,
            Error::KeyNotTrusted => Expect::KeyNotTrusted,
            _ => return None,
        })
    }
}

/// The verdict string of a result, for logs (defmt cannot format [`Error`]): the
/// [`Expect::name`] it stands for, or `OtherError`.
pub fn verdict_name(result: &Result<VerifiedImage<'_>, Error>) -> &'static str {
    Expect::of(result).map_or("OtherError", Expect::name)
}

/// A short name of a policy, for logs.
pub const fn policy_name(policy: Policy) -> &'static str {
    match policy {
        Policy::ClassicalOnly => "ClassicalOnly",
        Policy::PqOnly => "PqOnly",
        Policy::Hybrid => "Hybrid",
        _ => "unknown",
    }
}

/// Why an index could not be parsed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ParseError {
    /// The index does not start with [`MAGIC`].
    BadMagic,
    /// The header names a format version other than [`VERSION`].
    UnsupportedVersion(u16),
    /// A case name is not UTF-8.
    BadName,
    /// A case has a `pq_alg` byte other than 0..=3.
    UnknownAlgorithm(u8),
    /// A case has an expectation code outside [`Expect::ALL`].
    BadExpectation(u8),
    /// The input ends inside a header or a case.
    Truncated,
    /// Bytes remain after the declared number of cases.
    TrailingBytes,
}

/// One case of the index, borrowing from it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Case<'a> {
    /// The MANIFEST.json name of the image.
    pub name: &'a str,
    /// The algorithm of the image's post-quantum key, if it has one.
    pub algorithm: Option<Algorithm>,
    /// The image's post-quantum public key (empty without one).
    pub public_key: &'a [u8],
    /// The expected verdicts with the `ml-dsa` feature under [`Policy::ClassicalOnly`],
    /// [`Policy::PqOnly`] and [`Policy::Hybrid`], in [`Policy::ALL`] order.
    pub expect: [Expect; 3],
    /// The same without the `ml-dsa` feature (SHA-44).
    pub expect_without_ml_dsa: [Expect; 3],
}

impl Case<'_> {
    /// The expected verdict under `policy`, with the `ml-dsa` feature
    /// (`ml_dsa_enabled`) or without it.
    pub fn expect(&self, policy: Policy, ml_dsa_enabled: bool) -> Option<Expect> {
        let at = Policy::ALL.iter().position(|p| *p == policy)?;
        let set = if ml_dsa_enabled {
            &self.expect
        } else {
            &self.expect_without_ml_dsa
        };
        set.get(at).copied()
    }
}

/// A parsed index header plus the undecoded case bytes.
#[derive(Clone, Copy, Debug)]
pub struct Fixture<'a> {
    /// The number of cases.
    pub count: u16,
    body: &'a [u8],
}

impl<'a> Fixture<'a> {
    /// Parses the index header. The cases are decoded lazily by [`Fixture::cases`].
    pub fn parse(bytes: &'a [u8]) -> Result<Self, ParseError> {
        let mut rest = bytes;
        if take(&mut rest, MAGIC.len())? != MAGIC.as_slice() {
            return Err(ParseError::BadMagic);
        }
        let version = read_u16(&mut rest)?;
        if version != VERSION {
            return Err(ParseError::UnsupportedVersion(version));
        }
        let count = read_u16(&mut rest)?;
        Ok(Self { count, body: rest })
    }

    /// Iterates over the cases. After the first error the iterator ends.
    pub fn cases(&self) -> Cases<'a> {
        Cases {
            rest: self.body,
            remaining: self.count,
            done: false,
        }
    }

    /// The case for image `name`, if the index parses up to it.
    pub fn case(&self, name: &str) -> Option<Case<'a>> {
        self.cases().map_while(Result::ok).find(|c| c.name == name)
    }
}

/// Iterator over the cases of a [`Fixture`].
#[derive(Clone, Debug)]
pub struct Cases<'a> {
    rest: &'a [u8],
    remaining: u16,
    done: bool,
}

impl<'a> Iterator for Cases<'a> {
    type Item = Result<Case<'a>, ParseError>;

    fn next(&mut self) -> Option<Self::Item> {
        if self.done {
            return None;
        }
        if self.remaining == 0 {
            self.done = true;
            return (!self.rest.is_empty()).then_some(Err(ParseError::TrailingBytes));
        }
        self.remaining -= 1;
        let case = parse_case(&mut self.rest);
        if case.is_err() {
            self.done = true;
        }
        Some(case)
    }
}

fn parse_case<'a>(rest: &mut &'a [u8]) -> Result<Case<'a>, ParseError> {
    let name_len = usize::from(read_u8(rest)?);
    let name = core::str::from_utf8(take(rest, name_len)?).map_err(|_| ParseError::BadName)?;
    let algorithm = match read_u8(rest)? {
        0 => None,
        1 => Some(Algorithm::MlDsa44),
        2 => Some(Algorithm::MlDsa65),
        3 => Some(Algorithm::LmsHss),
        other => return Err(ParseError::UnknownAlgorithm(other)),
    };
    let pk_len = usize::from(read_u16(rest)?);
    let public_key = take(rest, pk_len)?;
    let mut expect = [Expect::Ok; 3];
    let mut expect_without_ml_dsa = [Expect::Ok; 3];
    for slot in expect.iter_mut().chain(expect_without_ml_dsa.iter_mut()) {
        let code = read_u8(rest)?;
        *slot = Expect::from_code(code).ok_or(ParseError::BadExpectation(code))?;
    }
    Ok(Case {
        name,
        algorithm,
        public_key,
        expect,
        expect_without_ml_dsa,
    })
}

fn take<'a>(rest: &mut &'a [u8], n: usize) -> Result<&'a [u8], ParseError> {
    let (head, tail) = rest.split_at_checked(n).ok_or(ParseError::Truncated)?;
    *rest = tail;
    Ok(head)
}

fn read_u8(rest: &mut &[u8]) -> Result<u8, ParseError> {
    let [b] = take_array::<1>(rest)?;
    Ok(b)
}

fn read_u16(rest: &mut &[u8]) -> Result<u16, ParseError> {
    take_array(rest).map(u16::from_le_bytes)
}

fn take_array<const N: usize>(rest: &mut &[u8]) -> Result<[u8; N], ParseError> {
    <[u8; N]>::try_from(take(rest, N)?).map_err(|_| ParseError::Truncated)
}

/// The trusted keys of a case: its post-quantum key (if any) and [`ED25519_TEST_KEY`].
pub fn trusted_keys<'a>(case: &Case<'a>) -> Result<TrustedKeys<'a, 1, 1>, KeySetError> {
    let ed25519 = [Ed25519Key {
        public_key: &ED25519_TEST_KEY,
    }];
    match case.algorithm {
        Some(algorithm) => TrustedKeys::with_ed25519(
            &[TrustedKey {
                algorithm,
                public_key: case.public_key,
            }],
            &ed25519,
        ),
        None => TrustedKeys::with_ed25519(&[], &ed25519),
    }
}

/// Where the images are read from: a slot reader per image (an in-memory slice on the
/// host, a `NorFlashReader` over the board flash at the image's address on target).
pub trait Slots {
    /// The reader of one image.
    type Reader<'s>: ImageReader
    where
        Self: 's;

    /// The reader of `image` (the [`IMAGES`] bytes of `name`), or `None` if it cannot be
    /// placed.
    fn slot(&mut self, name: &str, image: &'static [u8]) -> Option<Self::Reader<'_>>;
}

/// [`Slots`] over the images in memory (the `&[u8]` reader).
#[derive(Clone, Copy, Debug, Default)]
pub struct InMemory;

impl Slots for InMemory {
    type Reader<'s> = &'static [u8];

    fn slot(&mut self, _: &str, image: &'static [u8]) -> Option<&'static [u8]> {
        Some(image)
    }
}

/// What went wrong running a cell, besides a verdict mismatch.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CaseError {
    /// The index names an image that is not in [`IMAGES`].
    UnknownImage,
    /// The slot provider could not place the image.
    NoSlot,
    /// The case's key could not be put into a [`TrustedKeys`] set.
    KeySet(KeySetError),
}

/// The result of one cell (one case under one policy).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Outcome {
    /// The policy.
    pub policy: Policy,
    /// The expected verdict.
    pub expect: Expect,
    /// The verdict, or `None` if it is not one of the matrix's, or the cell could not run.
    pub got: Option<Expect>,
    /// Why the cell could not run.
    pub error: Option<CaseError>,
}

impl Outcome {
    /// True when the verdict is the expected one.
    pub fn passed(&self) -> bool {
        self.error.is_none() && self.got == Some(self.expect)
    }

    /// The verdict string, for logs.
    pub fn got_name(&self) -> &'static str {
        match (self.error, self.got) {
            (Some(CaseError::UnknownImage), _) => "UnknownImage",
            (Some(CaseError::NoSlot), _) => "NoSlot",
            (Some(CaseError::KeySet(_)), _) => "KeySetError",
            (None, Some(got)) => got.name(),
            (None, None) => "OtherError",
        }
    }
}

/// Run `case` under `policy`: [`verify_with`]`(backend, ..)` over the image's slot, with
/// [`trusted_keys`], the TLV areas read into `tlv_buf` and the body hashed through
/// `chunk`. The expectation is the case's `ml-dsa`-on or -off cell, as
/// [`Algorithm::is_enabled`] reports for this build.
#[inline(never)]
pub fn run_case<B: Backend + ?Sized, S: Slots>(
    backend: &B,
    slots: &mut S,
    case: &Case<'_>,
    policy: Policy,
    tlv_buf: &mut [u8],
    chunk: &mut [u8],
) -> Outcome {
    let expect = case
        .expect(policy, Algorithm::MlDsa44.is_enabled())
        .unwrap_or(Expect::Ok);
    let fail = |error| Outcome {
        policy,
        expect,
        got: None,
        error: Some(error),
    };
    let Some(data) = image(case.name) else {
        return fail(CaseError::UnknownImage);
    };
    let keys = match trusted_keys(case) {
        Ok(keys) => keys,
        Err(e) => return fail(CaseError::KeySet(e)),
    };
    let Some(mut reader) = slots.slot(case.name, data) else {
        return fail(CaseError::NoSlot);
    };
    let result = verify_with(backend, &mut reader, &keys, policy, tlv_buf, chunk);
    Outcome {
        policy,
        expect,
        got: Expect::of(&result),
        error: None,
    }
}

/// Totals for a whole index run.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Summary {
    /// Cells run (cases × policies).
    pub total: u32,
    /// Cells whose verdict was the expected one.
    pub passed: u32,
}

impl Summary {
    /// True when at least one cell ran and every cell passed.
    pub fn all_passed(&self) -> bool {
        self.total > 0 && self.passed == self.total
    }
}

/// Run every case of the index `bytes` under every policy of [`Policy::ALL`], calling
/// `log` with each outcome.
pub fn run_fixture<B: Backend + ?Sized, S: Slots>(
    bytes: &[u8],
    backend: &B,
    slots: &mut S,
    tlv_buf: &mut [u8],
    chunk: &mut [u8],
    mut log: impl FnMut(&Case<'_>, &Outcome),
) -> Result<Summary, ParseError> {
    let fixture = Fixture::parse(bytes)?;
    let mut summary = Summary::default();
    for case in fixture.cases() {
        let case = case?;
        for &policy in Policy::ALL {
            let outcome = run_case(backend, slots, &case, policy, tlv_buf, chunk);
            log(&case, &outcome);
            summary.total = summary.total.saturating_add(1);
            if outcome.passed() {
                summary.passed = summary.passed.saturating_add(1);
            }
        }
    }
    Ok(summary)
}
