//! C ABI for [`keelsign-verify`](mod@keelsign_verify): the static library
//! `libkeelsign.a` and its header `include/keelsign.h` (generated by cbindgen 0.29.4,
//! never edited by hand), for MCUboot's image-check hook (`boot_image_check_hook`,
//! docs/mcuboot.md) and other C callers.
//!
//! Three functions: `keelsign_verify` (verify an image held in memory under a policy and
//! a set of trusted keys), `keelsign_verify_cb` (the same, reading the image through a
//! caller-supplied [`keelsign_reader_t`] callback, for images in flash that is not
//! memory-mapped) and `keelsign_digest` (the image digest `M`). All return a
//! [`keelsign_status_t`]; every known `keelsign_verify::Error` variant has its own stable
//! code. The pointer and length contract of each function is in its documentation and in
//! docs/ffi.md.
//!
//! Build: `cargo build -p keelsign-ffi --profile ffi --locked [--target <triple>]
//! [--features ed25519,ml-dsa]` gives `target[/<triple>]/ffi/libkeelsign.a`. Default
//! features: LMS/HSS only.
//!
//! All `unsafe` is in the `abi` module; the rest of the crate is safe Rust.
//!
//! `no_std` in every build with `panic = "abort"`: the `ffi` profile and every bare-metal
//! target. Stable Rust cannot build a `no_std` static library with `panic = "unwind"`
//! ("unwinding panics are not supported without std"), which the host `dev` and `test`
//! profiles of `cargo build/clippy/test --workspace` use; those builds link `std` instead
//! and are never shipped.
#![cfg_attr(not(panic = "unwind"), no_std)]
#![deny(unsafe_code)]
#![deny(missing_docs)]
#![allow(non_camel_case_types)]

#[cfg(test)]
extern crate std;

#[allow(unsafe_code)]
mod abi;
mod status;

pub use abi::{keelsign_digest, keelsign_reader_t, keelsign_verify, keelsign_verify_cb};
pub use status::keelsign_status_t;

/// Version of this C ABI. Bumped on any incompatible change to the header.
pub const KEELSIGN_ABI_VERSION: u32 = 1;

/// The most post-quantum keys (`KEELSIGN_ALG_MLDSA44`, `KEELSIGN_ALG_MLDSA65`,
/// `KEELSIGN_ALG_LMS_HSS`) one `keelsign_verify` call accepts.
pub const KEELSIGN_MAX_PQ_KEYS: usize = 8;

/// The most Ed25519 keys (`KEELSIGN_ALG_ED25519`) one `keelsign_verify` call accepts.
pub const KEELSIGN_MAX_ED25519_KEYS: usize = 8;

/// Bytes of the stack buffer the TLV areas are copied into. Images whose TLV areas need
/// more fail with `KEELSIGN_ERR_TLV_AREA_TOO_LARGE`. Fits one ML-DSA-65 signature and the
/// usual MCUboot TLVs.
pub const KEELSIGN_TLV_BUF_LEN: usize = 4096;

/// Bytes of the stack buffer the image body is hashed through
/// (`keelsign_verify::DEFAULT_CHUNK_LEN`).
pub const KEELSIGN_CHUNK_LEN: usize = 256;
const _: () = assert!(KEELSIGN_CHUNK_LEN == keelsign_verify::DEFAULT_CHUNK_LEN);

/// `keelsign_result_t.pq_key_index` / `ed25519_key_index` when no key of that kind
/// verified the image.
pub const KEELSIGN_NO_KEY: u32 = 0xFFFF_FFFF;

/// A key algorithm (`KEELSIGN_ALG_*`).
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct keelsign_alg_t(pub u32);

/// ML-DSA-44 (FIPS 204); a raw 1312-byte public key. Needs the `ml-dsa` feature to verify.
pub const KEELSIGN_ALG_MLDSA44: keelsign_alg_t = keelsign_alg_t(1);
/// ML-DSA-65 (FIPS 204); a raw 1952-byte public key. Needs the `ml-dsa` feature to verify.
pub const KEELSIGN_ALG_MLDSA65: keelsign_alg_t = keelsign_alg_t(2);
/// LMS/HSS (RFC 8554, SP 800-208); a raw 52-byte (HSS L=1) or 60-byte public key.
pub const KEELSIGN_ALG_LMS_HSS: keelsign_alg_t = keelsign_alg_t(3);
/// Ed25519; the raw 32-byte public key. Needs the `ed25519` feature to verify.
pub const KEELSIGN_ALG_ED25519: keelsign_alg_t = keelsign_alg_t(4);

/// A verification policy (`KEELSIGN_POLICY_*`).
#[repr(transparent)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct keelsign_policy_t(pub u32);

/// The Ed25519 half only (MCUboot's KEYHASH + ED25519 pair). Needs the `ed25519` feature;
/// without it the call fails with `KEELSIGN_ERR_ED25519_NOT_ENABLED`.
pub const KEELSIGN_POLICY_CLASSICAL_ONLY: keelsign_policy_t = keelsign_policy_t(1);
/// The post-quantum half only (keelsign key ID + one PQ signature TLV).
pub const KEELSIGN_POLICY_PQ_ONLY: keelsign_policy_t = keelsign_policy_t(2);
/// Both halves over the same digest. Needs the `ed25519` feature; without it the call
/// fails with `KEELSIGN_ERR_ED25519_NOT_ENABLED`.
pub const KEELSIGN_POLICY_HYBRID: keelsign_policy_t = keelsign_policy_t(3);

/// One trusted public key. `key` must point to `key_len` readable bytes for the duration
/// of the call; nothing is retained after it returns.
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct keelsign_key_t {
    /// The key's algorithm.
    pub alg: keelsign_alg_t,
    /// The raw encoded public key (never NULL).
    pub key: *const u8,
    /// Bytes at `key`.
    pub key_len: usize,
}

/// What `keelsign_verify` reports about an image it accepted.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct keelsign_result_t {
    /// `ih_ver.iv_major`.
    pub major: u8,
    /// `ih_ver.iv_minor`.
    pub minor: u8,
    /// `ih_ver.iv_revision`.
    pub revision: u16,
    /// `ih_ver.iv_build_num`.
    pub build_num: u32,
    /// 1 if the protected TLV area holds a security counter, else 0.
    pub has_security_counter: u8,
    /// The security counter (0 when `has_security_counter` is 0).
    pub security_counter: u32,
    /// Bytes from the start of the image to the end of its TLV areas.
    pub image_len: u32,
    /// The image digest `M` (SHA-256 of header, body and protected TLVs).
    pub digest: [u8; 32],
    /// Index into the caller's `keys` array of the post-quantum key that verified the
    /// image, or `KEELSIGN_NO_KEY` (ClassicalOnly).
    pub pq_key_index: u32,
    /// Index into the caller's `keys` array of the Ed25519 key that verified the image,
    /// or `KEELSIGN_NO_KEY` (PqOnly).
    pub ed25519_key_index: u32,
}
