//! The keelsign sample images in `tests/fixtures/images/` (SHA-37), generated by
//! `scripts/gen_image_fixtures.py` from imgtool 2.4.0 output plus the keelsign TLVs, are
//! walked, their TLVs selected, and the LMS/HSS ones verified through `verify_pq` over
//! the image digest `M` (docs/image-format.md).
//!
//! The header / TLV walker below is test-local and deliberately minimal: it is not a
//! second parser, and SHA-35's `keelsign_verify` image parser replaces it.

// Host test code, not no_std firmware: failing a test with a message is the point.
#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing
)]

use std::fs;
use std::path::PathBuf;

use keelsign_verify::tlv::{
    KEELSIGN_TLV_RANGE, KEY_ID_LEN, TLV_KEELSIGN_KEY_ID, TLV_LMS_HSS_SIG, TLV_MLDSA44_SIG,
};
use keelsign_verify::{
    Algorithm, Error, TrustedKey, TrustedKeys, key_id_of, select_pq_signature, verify_pq,
};
use sha2::{Digest, Sha256};

const IMAGE_MAGIC: u32 = 0x96F3_B83D;
const TLV_INFO_MAGIC: u16 = 0x6907;
const TLV_PROT_INFO_MAGIC: u16 = 0x6908;
const TLV_KEYHASH: u16 = 0x0001;
const TLV_SHA256: u16 = 0x0010;
const TLV_ED25519: u16 = 0x0024;

/// Every fixture image, as named in MANIFEST.json.
const FIXTURES: [&str; 7] = [
    "keelsign-lms-m32-h5.bin",
    "keelsign-hss2-m32-h5h5.bin",
    "keelsign-lms-protected-tlvs.bin",
    "keelsign-hybrid-ed25519-lms.bin",
    "keelsign-mldsa44.bin",
    "keelsign-mldsa65.bin",
    "keelsign-dual-pq-invalid.bin",
];

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tests/fixtures/images")
}

fn read(rel: &str) -> Vec<u8> {
    let path = fixture_dir().join(rel);
    fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

// ---- Test-local walker (replaced by SHA-35) ----------------------------------------------

fn u16_at(data: &[u8], off: usize) -> u16 {
    u16::from_le_bytes([data[off], data[off + 1]])
}

fn u32_at(data: &[u8], off: usize) -> u32 {
    u32::from_le_bytes(data[off..off + 4].try_into().unwrap())
}

/// A walked image: header fields and the TLVs of each area as (type, value).
struct Walked<'a> {
    hdr_size: usize,
    img_size: usize,
    prot_size: usize,
    protected: Vec<(u16, &'a [u8])>,
    unprotected: Vec<(u16, &'a [u8])>,
}

impl Walked<'_> {
    /// The bytes the image digest covers: header, body and protected TLV area.
    fn signed_len(&self) -> usize {
        self.hdr_size + self.img_size + self.prot_size
    }
}

/// The TLVs of the area starting at `off` with info magic `magic`, and its `it_tlv_tot`.
fn walk_area(data: &[u8], off: usize, magic: u16) -> (Vec<(u16, &[u8])>, usize) {
    assert_eq!(u16_at(data, off), magic, "TLV info magic at {off:#x}");
    let tot = usize::from(u16_at(data, off + 2));
    let end = off + tot;
    assert!(end <= data.len(), "TLV area overruns the image");
    let mut tlvs = Vec::new();
    let mut at = off + 4;
    while at < end {
        let (kind, len) = (u16_at(data, at), usize::from(u16_at(data, at + 2)));
        assert!(at + 4 + len <= end, "TLV {kind:#06x} overruns its area");
        tlvs.push((kind, &data[at + 4..at + 4 + len]));
        at += 4 + len;
    }
    (tlvs, tot)
}

fn walk(data: &[u8]) -> Walked<'_> {
    assert_eq!(u32_at(data, 0), IMAGE_MAGIC, "image magic");
    let hdr_size = usize::from(u16_at(data, 8));
    let prot_size = usize::from(u16_at(data, 10));
    let img_size = u32_at(data, 12) as usize;
    let tlv_off = hdr_size + img_size;
    let protected = if prot_size == 0 {
        Vec::new()
    } else {
        let (tlvs, tot) = walk_area(data, tlv_off, TLV_PROT_INFO_MAGIC);
        assert_eq!(
            tot, prot_size,
            "ih_protect_tlv_size == protected it_tlv_tot"
        );
        tlvs
    };
    let (unprotected, tot) = walk_area(data, tlv_off + prot_size, TLV_INFO_MAGIC);
    assert_eq!(
        tlv_off + prot_size + tot,
        data.len(),
        "no bytes after the TLVs"
    );
    Walked {
        hdr_size,
        img_size,
        prot_size,
        protected,
        unprotected,
    }
}

// ---- Manifest ------------------------------------------------------------------------------

/// The fixture's entry in MANIFEST.json (brace-matched; the manifest has no braces in
/// strings).
fn manifest_entry(name: &str) -> String {
    let manifest = String::from_utf8(read("MANIFEST.json")).unwrap();
    let start = manifest
        .find(&format!("\"{name}\": {{"))
        .unwrap_or_else(|| panic!("MANIFEST.json has no entry `{name}`"));
    let body = &manifest[start..];
    let open = body.find('{').unwrap();
    let mut depth = 0;
    for (i, c) in body[open..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return body[open..=open + i].to_owned();
                }
            }
            _ => {}
        }
    }
    panic!("unterminated entry `{name}`");
}

/// A scalar field of a manifest entry, without quotes (lists are space-separated).
fn field(entry: &str, name: &str) -> String {
    let needle = format!("\"{name}\": ");
    let start = entry
        .find(&needle)
        .unwrap_or_else(|| panic!("no field `{name}`"))
        + needle.len();
    let rest = &entry[start..];
    let end = rest.find([',', '\n']).unwrap_or(rest.len());
    rest[..end].trim().trim_matches('"').to_owned()
}

fn hex(text: &str) -> Vec<u8> {
    assert!(text.len().is_multiple_of(2), "odd hex length");
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).unwrap())
        .collect()
}

fn tlv_list(text: &str) -> Vec<u16> {
    text.split_whitespace()
        .map(|s| u16::from_str_radix(s.trim_start_matches("0x"), 16).unwrap())
        .collect()
}

fn algorithm(name: &str) -> Algorithm {
    match name {
        "LmsHss" => Algorithm::LmsHss,
        "MlDsa44" => Algorithm::MlDsa44,
        "MlDsa65" => Algorithm::MlDsa65,
        other => panic!("unknown algorithm {other}"),
    }
}

fn sha256(data: &[u8]) -> [u8; 32] {
    Sha256::digest(data).into()
}

/// `verify_pq` of an image's unprotected TLVs over `digest`, trusting only `public_key`.
fn verify_image(
    walked: &Walked<'_>,
    alg: Algorithm,
    public_key: &[u8],
    digest: &[u8],
) -> Result<(), Error> {
    let keys = TrustedKeys::<2>::new(&[TrustedKey {
        algorithm: alg,
        public_key,
    }])
    .unwrap();
    verify_pq(&keys, walked.unprotected.iter().copied(), digest).map(|_| ())
}

// ---- Tests ---------------------------------------------------------------------------------

#[test]
fn every_fixture_walks_and_selects_expected_tlvs() {
    for name in FIXTURES {
        let data = read(name);
        let entry = manifest_entry(name);
        let walked = walk(&data);

        let kinds: Vec<u16> = walked.unprotected.iter().map(|(k, _)| *k).collect();
        assert_eq!(
            kinds,
            tlv_list(&field(&entry, "unprotected_tlvs")),
            "{name}"
        );
        let prot: Vec<u16> = walked.protected.iter().map(|(k, _)| *k).collect();
        assert_eq!(prot, tlv_list(&field(&entry, "protected_tlvs")), "{name}");
        assert_eq!(walked.hdr_size, 0x200, "{name}");
        assert_eq!(walked.img_size, 1536, "{name}");

        // Every keelsign TLV is unprotected, after the MCUboot TLVs, in the keelsign block.
        assert!(
            walked
                .protected
                .iter()
                .all(|(k, _)| !KEELSIGN_TLV_RANGE.contains(k)),
            "{name}: keelsign TLV in the protected area"
        );
        let first_keelsign = kinds
            .iter()
            .position(|k| KEELSIGN_TLV_RANGE.contains(k))
            .unwrap();
        assert!(
            kinds[first_keelsign..]
                .iter()
                .all(|k| KEELSIGN_TLV_RANGE.contains(k)),
            "{name}: MCUboot TLVs come first"
        );
        assert_eq!(kinds[first_keelsign], TLV_KEELSIGN_KEY_ID, "{name}");

        // M is the SHA256 TLV, and exactly one SHA256 TLV is present.
        let digest = sha256(&data[..walked.signed_len()]);
        let sha: Vec<&[u8]> = walked
            .unprotected
            .iter()
            .filter(|(k, _)| *k == TLV_SHA256)
            .map(|(_, v)| *v)
            .collect();
        assert_eq!(sha, [digest.as_slice()], "{name}: SHA256 TLV");
        assert_eq!(digest.to_vec(), hex(&field(&entry, "digest_hex")), "{name}");

        let public_key = hex(&field(&entry, "public_key_hex"));
        let key_id = hex(&field(&entry, "key_id_hex"));
        assert_eq!(key_id.len(), KEY_ID_LEN);
        assert_eq!(key_id, key_id_of(&public_key), "{name}: key ID");
        let alg = algorithm(&field(&entry, "algorithm"));
        let sig_lens: Vec<usize> = field(&entry, "signature_lens")
            .split_whitespace()
            .map(|s| s.parse().unwrap())
            .collect();

        let expect = field(&entry, "expect_verify_pq");
        let selected = select_pq_signature(walked.unprotected.iter().copied());
        if expect == "MultiplePqSignatures" {
            assert_eq!(selected, Err(Error::MultiplePqSignatures), "{name}");
            continue;
        }
        let selected = selected.unwrap();
        assert_eq!(selected.algorithm, alg, "{name}");
        assert_eq!(selected.key_id, key_id.as_slice(), "{name}");
        assert_eq!(sig_lens, [selected.signature.len()], "{name}");
        let expected_len = match alg {
            Algorithm::MlDsa44 => Some(2420),
            Algorithm::MlDsa65 => Some(3309),
            _ => None,
        };
        if let Some(len) = expected_len {
            assert_eq!(selected.signature.len(), len, "{name}");
            assert_eq!(Some(public_key.len()), alg.public_key_len(), "{name}");
            assert_eq!(field(&entry, "verifiable"), "false", "{name}");
            // ML-DSA is not verified yet (SHA-44): off, the dispatcher refuses it; on,
            // DefaultBackend does. Both give UnsupportedAlgorithm.
            assert_eq!(expect, "UnsupportedAlgorithm", "{name}");
            assert_eq!(
                verify_image(&walked, alg, &public_key, &digest),
                Err(Error::UnsupportedAlgorithm(alg)),
                "{name}"
            );
        } else {
            assert_eq!(field(&entry, "verifiable"), "true", "{name}");
            assert_eq!(expect, "Ok", "{name}");
        }
    }
}

#[test]
fn lms_fixtures_verify_through_verify_pq() {
    let mut verified = 0;
    for name in FIXTURES {
        let entry = manifest_entry(name);
        if field(&entry, "verifiable") != "true" {
            continue;
        }
        let data = read(name);
        let walked = walk(&data);
        let public_key = hex(&field(&entry, "public_key_hex"));
        // M computed over header || body || protected TLV area, equal to the SHA256 TLV.
        let digest = sha256(&data[..walked.signed_len()]);
        let sha_tlv = walked
            .unprotected
            .iter()
            .find(|(k, _)| *k == TLV_SHA256)
            .unwrap()
            .1;
        assert_eq!(sha_tlv, digest.as_slice(), "{name}");
        assert_eq!(
            verify_image(&walked, Algorithm::LmsHss, &public_key, &digest),
            Ok(()),
            "{name}"
        );
        // Any other message fails.
        let mut other = digest;
        other[31] ^= 1;
        assert_eq!(
            verify_image(&walked, Algorithm::LmsHss, &public_key, &other),
            Err(Error::SignatureInvalid),
            "{name}"
        );
        verified += 1;
    }
    assert_eq!(verified, 4, "four LMS/HSS fixtures verify");
}

#[test]
fn dual_pq_fixture_is_multiple_pq_signatures() {
    let name = "keelsign-dual-pq-invalid.bin";
    let data = read(name);
    let walked = walk(&data);
    let entry = manifest_entry(name);
    let kinds: Vec<u16> = walked.unprotected.iter().map(|(k, _)| *k).collect();
    assert_eq!(
        kinds,
        [
            TLV_SHA256,
            TLV_KEELSIGN_KEY_ID,
            TLV_LMS_HSS_SIG,
            TLV_MLDSA44_SIG
        ]
    );
    let public_key = hex(&field(&entry, "public_key_hex"));
    let digest = sha256(&data[..walked.signed_len()]);
    // Fails closed even though the LMS signature alone is valid for the trusted key.
    assert_eq!(
        verify_image(&walked, Algorithm::LmsHss, &public_key, &digest),
        Err(Error::MultiplePqSignatures)
    );
    let lms_only: Vec<(u16, &[u8])> = walked
        .unprotected
        .iter()
        .copied()
        .filter(|(k, _)| *k != TLV_MLDSA44_SIG)
        .collect();
    let keys = TrustedKeys::<1>::new(&[TrustedKey {
        algorithm: Algorithm::LmsHss,
        public_key: &public_key,
    }])
    .unwrap();
    assert!(verify_pq(&keys, lms_only, &digest).is_ok());
    assert_eq!(field(&entry, "expect_verify_pq"), "MultiplePqSignatures");
}

#[test]
fn digest_covers_protected_tlvs() {
    let name = "keelsign-lms-protected-tlvs.bin";
    let data = read(name);
    let walked = walk(&data);
    let entry = manifest_entry(name);
    let public_key = hex(&field(&entry, "public_key_hex"));
    assert_eq!(
        walked.protected.iter().map(|(k, _)| *k).collect::<Vec<_>>(),
        [0x0050, 0x10A0],
        "SEC_CNT and a vendor TLV, protected"
    );
    assert!(walked.prot_size > 0);

    let digest = sha256(&data[..walked.signed_len()]);
    let without_protected = sha256(&data[..walked.hdr_size + walked.img_size]);
    assert_ne!(digest, without_protected);
    let sha_tlv = walked
        .unprotected
        .iter()
        .find(|(k, _)| *k == TLV_SHA256)
        .unwrap()
        .1;
    assert_eq!(sha_tlv, digest.as_slice());
    assert_ne!(sha_tlv, without_protected.as_slice());
    assert_eq!(
        verify_image(&walked, Algorithm::LmsHss, &public_key, &digest),
        Ok(())
    );
    // The digest without the protected area does not verify.
    assert_eq!(
        verify_image(&walked, Algorithm::LmsHss, &public_key, &without_protected),
        Err(Error::SignatureInvalid)
    );
    // Changing one byte of a protected TLV value (the vendor TLV's last byte) changes M,
    // and the signature no longer verifies.
    let mut tampered = data.clone();
    let last_protected = walked.signed_len() - 1;
    tampered[last_protected] ^= 0x01;
    let tampered_walk = walk(&tampered);
    let tampered_digest = sha256(&tampered[..tampered_walk.signed_len()]);
    assert_ne!(tampered_digest, digest);
    assert_eq!(
        verify_image(
            &tampered_walk,
            Algorithm::LmsHss,
            &public_key,
            &tampered_digest
        ),
        Err(Error::SignatureInvalid)
    );
}

#[test]
fn hybrid_fixture_has_one_keyhash_ed25519_pair_before_keelsign_tlvs() {
    let name = "keelsign-hybrid-ed25519-lms.bin";
    let data = read(name);
    let walked = walk(&data);
    let entry = manifest_entry(name);
    assert_eq!(field(&entry, "ed25519"), "true");
    let kinds: Vec<u16> = walked.unprotected.iter().map(|(k, _)| *k).collect();
    assert_eq!(
        kinds,
        [
            TLV_SHA256,
            TLV_KEYHASH,
            TLV_ED25519,
            TLV_KEELSIGN_KEY_ID,
            TLV_LMS_HSS_SIG
        ]
    );
    assert_eq!(kinds.iter().filter(|&&k| k == TLV_KEYHASH).count(), 1);
    assert_eq!(kinds.iter().filter(|&&k| k == TLV_ED25519).count(), 1);
    let keyhash_at = kinds.iter().position(|&k| k == TLV_KEYHASH).unwrap();
    assert_eq!(
        kinds[keyhash_at + 1],
        TLV_ED25519,
        "KEYHASH immediately precedes ED25519"
    );
    let first_keelsign = kinds
        .iter()
        .position(|k| KEELSIGN_TLV_RANGE.contains(k))
        .unwrap();
    assert!(keyhash_at + 1 < first_keelsign, "MCUboot pair first");

    // KEYHASH is the full SHA-256 of the test key's DER SubjectPublicKeyInfo.
    let spki = read("keys/ed25519-test-key.spki.der");
    assert_eq!(spki.len(), 44);
    let keyhash = walked.unprotected[keyhash_at].1;
    assert_eq!(keyhash.len(), 32);
    assert_eq!(keyhash, sha256(&spki).as_slice());
    assert_eq!(walked.unprotected[keyhash_at + 1].1.len(), 64, "ED25519");

    // The PQ half verifies over the same M the Ed25519 signature covers.
    let public_key = hex(&field(&entry, "public_key_hex"));
    let digest = sha256(&data[..walked.signed_len()]);
    assert_eq!(
        verify_image(&walked, Algorithm::LmsHss, &public_key, &digest),
        Ok(())
    );
}
