//! The chunked image digest (SHA-42) over every fixture image in `tests/fixtures/images/`
//! (generated by `scripts/gen_image_fixtures.py`): `Image::read_from` plus
//! `image_digest` through the `&[u8]` reader equals the image's `SHA256` TLV (what
//! imgtool computed) and the `digest_hex` MANIFEST.json records.

// Host test code, not no_std firmware: failing a test with a message is the point.
#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing
)]

use std::fs;
use std::path::PathBuf;

use keelsign_verify::image::{IMAGE_TLV_SHA256, Image};
use keelsign_verify::{DEFAULT_CHUNK_LEN, image_digest};

/// Every little-endian signed fixture image, as named in MANIFEST.json (the SHA-46
/// policy mutations are not: some change the SHA256 TLV or the hashed bytes on purpose).
const FIXTURES: [&str; 17] = [
    "mcuboot-rsa2048.bin",
    "mcuboot-ecdsa-p256.bin",
    "mcuboot-ed25519.bin",
    "mcuboot-ed25519-padded.bin",
    "mcuboot-ed25519-200k.bin",
    "keelsign-lms-m32-h5.bin",
    "keelsign-hss2-m32-h5h5.bin",
    "keelsign-lms-protected-tlvs.bin",
    "keelsign-hybrid-ed25519-lms.bin",
    "keelsign-mldsa44.bin",
    "keelsign-mldsa65.bin",
    "keelsign-dual-pq-invalid.bin",
    "keelsign-hybrid-ed25519-mldsa44.bin",
    "keelsign-hybrid-protected-tlvs.bin",
    "keelsign-hybrid-reserved-tlv-protected.bin",
    "keelsign-mldsa44-protected-tlvs.bin",
    "keelsign-mldsa65-protected-tlvs.bin",
];

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tests/fixtures/images")
}

fn read(rel: &str) -> Vec<u8> {
    let path = fixture_dir().join(rel);
    fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// The `digest_hex` of a fixture's MANIFEST.json entry.
fn manifest_digest(name: &str) -> String {
    let manifest = String::from_utf8(read("MANIFEST.json")).unwrap();
    let start = manifest
        .find(&format!("\"{name}\": {{"))
        .unwrap_or_else(|| panic!("MANIFEST.json has no entry `{name}`"));
    let needle = "\"digest_hex\": \"";
    let at = manifest[start..].find(needle).unwrap() + start + needle.len();
    manifest[at..at + 64].to_owned()
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// `read_from` then `image_digest` through the in-memory reader; returns the digest and
/// the SHA256 TLV.
fn digest_and_tlv(data: &[u8], chunk_len: usize) -> ([u8; 32], Vec<u8>) {
    let mut reader = data;
    let mut tlv_buf = [0u8; 8192];
    let image = Image::read_from(&mut reader, &mut tlv_buf).unwrap();
    let mut chunk = vec![0u8; chunk_len];
    let digest = image_digest(&mut reader, &image, &mut chunk).unwrap();
    let tlv = image
        .unprotected()
        .pairs()
        .filter(|(t, _)| *t == IMAGE_TLV_SHA256)
        .map(|(_, v)| v.to_vec())
        .collect::<Vec<_>>();
    assert_eq!(tlv.len(), 1, "one SHA256 TLV");
    (digest, tlv.into_iter().next().unwrap())
}

#[test]
fn digest_matches_sha256_tlv_for_every_fixture() {
    for name in FIXTURES {
        let data = read(name);
        let (digest, tlv) = digest_and_tlv(&data, DEFAULT_CHUNK_LEN);
        assert_eq!(digest.as_slice(), tlv.as_slice(), "{name}");
        assert_eq!(hex(&digest), manifest_digest(name), "{name}");
    }
}

#[test]
fn golden_rsa_ecdsa_ed25519_digest_matches_sha256_tlv() {
    for name in [
        "mcuboot-rsa2048.bin",
        "mcuboot-ecdsa-p256.bin",
        "mcuboot-ed25519.bin",
    ] {
        let data = read(name);
        for chunk_len in [1, 64, DEFAULT_CHUNK_LEN, 4096] {
            let (digest, tlv) = digest_and_tlv(&data, chunk_len);
            assert_eq!(
                digest.as_slice(),
                tlv.as_slice(),
                "{name} chunk {chunk_len}"
            );
        }
    }
}
