//! The keelsign sample images in `tests/fixtures/images/` (SHA-37), generated by
//! `scripts/gen_image_fixtures.py` from imgtool 2.4.0 output plus the keelsign TLVs, are
//! parsed with `keelsign_verify::image` (SHA-35), their TLVs selected, and the LMS/HSS
//! ones verified through `verify_pq` over the image digest `M` (docs/image-format.md).
//! The golden MCUboot images (SHA-35) are parsed and checked against MANIFEST.json.

// Host test code, not no_std firmware: failing a test with a message is the point.
#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing
)]

use std::fs;
use std::path::PathBuf;

use keelsign_verify::image::{Image, ParseError};
use keelsign_verify::tlv::{
    KEELSIGN_TLV_RANGE, KEY_ID_LEN, TLV_KEELSIGN_KEY_ID, TLV_LMS_HSS_SIG, TLV_MLDSA44_SIG,
};
use keelsign_verify::{
    Algorithm, Error, TrustedKey, TrustedKeys, key_id_of, select_pq_signature, verify_pq,
};
use sha2::{Digest, Sha256};

const TLV_KEYHASH: u16 = 0x0001;
const TLV_SHA256: u16 = 0x0010;
const TLV_ED25519: u16 = 0x0024;

/// Every fixture image, as named in MANIFEST.json.
const FIXTURES: [&str; 7] = [
    "keelsign-lms-m32-h5.bin",
    "keelsign-hss2-m32-h5h5.bin",
    "keelsign-lms-protected-tlvs.bin",
    "keelsign-hybrid-ed25519-lms.bin",
    "keelsign-mldsa44.bin",
    "keelsign-mldsa65.bin",
    "keelsign-dual-pq-invalid.bin",
];

/// The golden MCUboot images (SHA-35), as named in MANIFEST.json.
const GOLDEN: [&str; 5] = [
    "mcuboot-rsa2048.bin",
    "mcuboot-ecdsa-p256.bin",
    "mcuboot-ed25519.bin",
    "mcuboot-ed25519-padded.bin",
    "rejected/mcuboot-ed25519-bigendian.bin",
];

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tests/fixtures/images")
}

fn read(rel: &str) -> Vec<u8> {
    let path = fixture_dir().join(rel);
    fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// The unprotected TLVs of an image, as (type, value).
fn unprotected<'a>(image: &Image<'a>) -> Vec<(u16, &'a [u8])> {
    image.unprotected().pairs().collect()
}

/// The protected TLVs of an image, as (type, value).
fn protected<'a>(image: &Image<'a>) -> Vec<(u16, &'a [u8])> {
    image
        .protected()
        .map(|area| area.pairs().collect())
        .unwrap_or_default()
}

/// The bytes the image digest covers: header, body and protected TLV area.
fn signed<'a>(data: &'a [u8], image: &Image<'_>) -> &'a [u8] {
    let range = image.hashed_range();
    &data[range.start as usize..range.end as usize]
}

// ---- Manifest ------------------------------------------------------------------------------

/// The fixture's entry in MANIFEST.json (brace-matched; the manifest has no braces in
/// strings).
fn manifest_entry(name: &str) -> String {
    let manifest = String::from_utf8(read("MANIFEST.json")).unwrap();
    let start = manifest
        .find(&format!("\"{name}\": {{"))
        .unwrap_or_else(|| panic!("MANIFEST.json has no entry `{name}`"));
    let body = &manifest[start..];
    let open = body.find('{').unwrap();
    let mut depth = 0;
    for (i, c) in body[open..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return body[open..=open + i].to_owned();
                }
            }
            _ => {}
        }
    }
    panic!("unterminated entry `{name}`");
}

/// A scalar field of a manifest entry, without quotes (lists are space-separated).
fn field(entry: &str, name: &str) -> String {
    let needle = format!("\"{name}\": ");
    let start = entry
        .find(&needle)
        .unwrap_or_else(|| panic!("no field `{name}`"))
        + needle.len();
    let rest = &entry[start..];
    let end = rest.find([',', '\n']).unwrap_or(rest.len());
    rest[..end].trim().trim_matches('"').to_owned()
}

fn hex(text: &str) -> Vec<u8> {
    assert!(text.len().is_multiple_of(2), "odd hex length");
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).unwrap())
        .collect()
}

fn tlv_list(text: &str) -> Vec<u16> {
    text.split_whitespace()
        .map(|s| u16::from_str_radix(s.trim_start_matches("0x"), 16).unwrap())
        .collect()
}

fn algorithm(name: &str) -> Algorithm {
    match name {
        "LmsHss" => Algorithm::LmsHss,
        "MlDsa44" => Algorithm::MlDsa44,
        "MlDsa65" => Algorithm::MlDsa65,
        other => panic!("unknown algorithm {other}"),
    }
}

fn sha256(data: &[u8]) -> [u8; 32] {
    Sha256::digest(data).into()
}

/// `verify_pq` of an image's unprotected TLVs over `digest`, trusting only `public_key`.
fn verify_image(
    image: &Image<'_>,
    alg: Algorithm,
    public_key: &[u8],
    digest: &[u8],
) -> Result<(), Error> {
    let keys = TrustedKeys::<2>::new(&[TrustedKey {
        algorithm: alg,
        public_key,
    }])
    .unwrap();
    verify_pq(&keys, image.unprotected().pairs(), digest).map(|_| ())
}

// ---- Tests ---------------------------------------------------------------------------------

#[test]
fn every_fixture_walks_and_selects_expected_tlvs() {
    for name in FIXTURES {
        let data = read(name);
        let entry = manifest_entry(name);
        let image = Image::parse(&data).unwrap();

        let kinds: Vec<u16> = unprotected(&image).iter().map(|(k, _)| *k).collect();
        assert_eq!(
            kinds,
            tlv_list(&field(&entry, "unprotected_tlvs")),
            "{name}"
        );
        let prot: Vec<u16> = protected(&image).iter().map(|(k, _)| *k).collect();
        assert_eq!(prot, tlv_list(&field(&entry, "protected_tlvs")), "{name}");
        assert_eq!(image.header().hdr_size, 0x200, "{name}");
        assert_eq!(image.header().img_size, 1536, "{name}");
        assert_eq!(
            image.tlv_end() as usize,
            data.len(),
            "{name}: no bytes after the TLVs"
        );

        // Every keelsign TLV is unprotected, after the MCUboot TLVs, in the keelsign block.
        assert!(
            protected(&image)
                .iter()
                .all(|(k, _)| !KEELSIGN_TLV_RANGE.contains(k)),
            "{name}: keelsign TLV in the protected area"
        );
        let first_keelsign = kinds
            .iter()
            .position(|k| KEELSIGN_TLV_RANGE.contains(k))
            .unwrap();
        assert!(
            kinds[first_keelsign..]
                .iter()
                .all(|k| KEELSIGN_TLV_RANGE.contains(k)),
            "{name}: MCUboot TLVs come first"
        );
        assert_eq!(kinds[first_keelsign], TLV_KEELSIGN_KEY_ID, "{name}");

        // M is the SHA256 TLV, and exactly one SHA256 TLV is present.
        let digest = sha256(signed(&data, &image));
        let sha: Vec<&[u8]> = unprotected(&image)
            .iter()
            .filter(|(k, _)| *k == TLV_SHA256)
            .map(|(_, v)| *v)
            .collect();
        assert_eq!(sha, [digest.as_slice()], "{name}: SHA256 TLV");
        assert_eq!(digest.to_vec(), hex(&field(&entry, "digest_hex")), "{name}");

        let public_key = hex(&field(&entry, "public_key_hex"));
        let key_id = hex(&field(&entry, "key_id_hex"));
        assert_eq!(key_id.len(), KEY_ID_LEN);
        assert_eq!(key_id, key_id_of(&public_key), "{name}: key ID");
        let alg = algorithm(&field(&entry, "algorithm"));
        let sig_lens: Vec<usize> = field(&entry, "signature_lens")
            .split_whitespace()
            .map(|s| s.parse().unwrap())
            .collect();

        let expect = field(&entry, "expect_verify_pq");
        let selected = select_pq_signature(image.unprotected().pairs());
        if expect == "MultiplePqSignatures" {
            assert_eq!(selected, Err(Error::MultiplePqSignatures), "{name}");
            continue;
        }
        let selected = selected.unwrap();
        assert_eq!(selected.algorithm, alg, "{name}");
        assert_eq!(selected.key_id, key_id.as_slice(), "{name}");
        assert_eq!(sig_lens, [selected.signature.len()], "{name}");
        let expected_len = match alg {
            Algorithm::MlDsa44 => Some(2420),
            Algorithm::MlDsa65 => Some(3309),
            _ => None,
        };
        if let Some(len) = expected_len {
            assert_eq!(selected.signature.len(), len, "{name}");
            assert_eq!(Some(public_key.len()), alg.public_key_len(), "{name}");
            assert_eq!(field(&entry, "verifiable"), "false", "{name}");
            // ML-DSA is not verified yet (SHA-44): off, the dispatcher refuses it; on,
            // DefaultBackend does. Both give UnsupportedAlgorithm.
            assert_eq!(expect, "UnsupportedAlgorithm", "{name}");
            assert_eq!(
                verify_image(&image, alg, &public_key, &digest),
                Err(Error::UnsupportedAlgorithm(alg)),
                "{name}"
            );
        } else {
            assert_eq!(field(&entry, "verifiable"), "true", "{name}");
            assert_eq!(expect, "Ok", "{name}");
        }
    }
}

#[test]
fn lms_fixtures_verify_through_verify_pq() {
    let mut verified = 0;
    for name in FIXTURES {
        let entry = manifest_entry(name);
        if field(&entry, "verifiable") != "true" {
            continue;
        }
        let data = read(name);
        let image = Image::parse(&data).unwrap();
        let public_key = hex(&field(&entry, "public_key_hex"));
        // M computed over header || body || protected TLV area, equal to the SHA256 TLV.
        let digest = sha256(signed(&data, &image));
        let sha_tlv = unprotected(&image)
            .iter()
            .find(|(k, _)| *k == TLV_SHA256)
            .unwrap()
            .1;
        assert_eq!(sha_tlv, digest.as_slice(), "{name}");
        assert_eq!(
            verify_image(&image, Algorithm::LmsHss, &public_key, &digest),
            Ok(()),
            "{name}"
        );
        // Any other message fails.
        let mut other = digest;
        other[31] ^= 1;
        assert_eq!(
            verify_image(&image, Algorithm::LmsHss, &public_key, &other),
            Err(Error::SignatureInvalid),
            "{name}"
        );
        verified += 1;
    }
    assert_eq!(verified, 4, "four LMS/HSS fixtures verify");
}

#[test]
fn dual_pq_fixture_is_multiple_pq_signatures() {
    let name = "keelsign-dual-pq-invalid.bin";
    let data = read(name);
    let image = Image::parse(&data).unwrap();
    let entry = manifest_entry(name);
    let kinds: Vec<u16> = unprotected(&image).iter().map(|(k, _)| *k).collect();
    assert_eq!(
        kinds,
        [
            TLV_SHA256,
            TLV_KEELSIGN_KEY_ID,
            TLV_LMS_HSS_SIG,
            TLV_MLDSA44_SIG
        ]
    );
    let public_key = hex(&field(&entry, "public_key_hex"));
    let digest = sha256(signed(&data, &image));
    // Fails closed even though the LMS signature alone is valid for the trusted key.
    assert_eq!(
        verify_image(&image, Algorithm::LmsHss, &public_key, &digest),
        Err(Error::MultiplePqSignatures)
    );
    let lms_only: Vec<(u16, &[u8])> = unprotected(&image)
        .iter()
        .copied()
        .filter(|(k, _)| *k != TLV_MLDSA44_SIG)
        .collect();
    let keys = TrustedKeys::<1>::new(&[TrustedKey {
        algorithm: Algorithm::LmsHss,
        public_key: &public_key,
    }])
    .unwrap();
    assert!(verify_pq(&keys, lms_only, &digest).is_ok());
    assert_eq!(field(&entry, "expect_verify_pq"), "MultiplePqSignatures");
}

#[test]
fn digest_covers_protected_tlvs() {
    let name = "keelsign-lms-protected-tlvs.bin";
    let data = read(name);
    let image = Image::parse(&data).unwrap();
    let entry = manifest_entry(name);
    let public_key = hex(&field(&entry, "public_key_hex"));
    assert_eq!(
        protected(&image)
            .iter()
            .map(|(k, _)| *k)
            .collect::<Vec<_>>(),
        [0x0050, 0x10A0],
        "SEC_CNT and a vendor TLV, protected"
    );
    assert!(image.header().protect_tlv_size > 0);

    let digest = sha256(signed(&data, &image));
    let without_protected = sha256(&data[..image.header().tlv_offset().unwrap() as usize]);
    assert_ne!(digest, without_protected);
    let sha_tlv = unprotected(&image)
        .iter()
        .find(|(k, _)| *k == TLV_SHA256)
        .unwrap()
        .1;
    assert_eq!(sha_tlv, digest.as_slice());
    assert_ne!(sha_tlv, without_protected.as_slice());
    assert_eq!(
        verify_image(&image, Algorithm::LmsHss, &public_key, &digest),
        Ok(())
    );
    // The digest without the protected area does not verify.
    assert_eq!(
        verify_image(&image, Algorithm::LmsHss, &public_key, &without_protected),
        Err(Error::SignatureInvalid)
    );
    // Changing one byte of a protected TLV value (the vendor TLV's last byte) changes M,
    // and the signature no longer verifies.
    let mut tampered = data.clone();
    let last_protected = image.hashed_range().end as usize - 1;
    tampered[last_protected] ^= 0x01;
    let tampered_image = Image::parse(&tampered).unwrap();
    let tampered_digest = sha256(signed(&tampered, &tampered_image));
    assert_ne!(tampered_digest, digest);
    assert_eq!(
        verify_image(
            &tampered_image,
            Algorithm::LmsHss,
            &public_key,
            &tampered_digest
        ),
        Err(Error::SignatureInvalid)
    );
}

#[test]
fn hybrid_fixture_has_one_keyhash_ed25519_pair_before_keelsign_tlvs() {
    let name = "keelsign-hybrid-ed25519-lms.bin";
    let data = read(name);
    let image = Image::parse(&data).unwrap();
    let entry = manifest_entry(name);
    assert_eq!(field(&entry, "ed25519"), "true");
    let kinds: Vec<u16> = unprotected(&image).iter().map(|(k, _)| *k).collect();
    assert_eq!(
        kinds,
        [
            TLV_SHA256,
            TLV_KEYHASH,
            TLV_ED25519,
            TLV_KEELSIGN_KEY_ID,
            TLV_LMS_HSS_SIG
        ]
    );
    assert_eq!(kinds.iter().filter(|&&k| k == TLV_KEYHASH).count(), 1);
    assert_eq!(kinds.iter().filter(|&&k| k == TLV_ED25519).count(), 1);
    let keyhash_at = kinds.iter().position(|&k| k == TLV_KEYHASH).unwrap();
    assert_eq!(
        kinds[keyhash_at + 1],
        TLV_ED25519,
        "KEYHASH immediately precedes ED25519"
    );
    let first_keelsign = kinds
        .iter()
        .position(|k| KEELSIGN_TLV_RANGE.contains(k))
        .unwrap();
    assert!(keyhash_at + 1 < first_keelsign, "MCUboot pair first");

    // KEYHASH is the full SHA-256 of the test key's DER SubjectPublicKeyInfo.
    let spki = read("keys/ed25519-test-key.spki.der");
    assert_eq!(spki.len(), 44);
    let keyhash = unprotected(&image)[keyhash_at].1;
    assert_eq!(keyhash.len(), 32);
    assert_eq!(keyhash, sha256(&spki).as_slice());
    assert_eq!(unprotected(&image)[keyhash_at + 1].1.len(), 64, "ED25519");

    // The PQ half verifies over the same M the Ed25519 signature covers.
    let public_key = hex(&field(&entry, "public_key_hex"));
    let digest = sha256(signed(&data, &image));
    assert_eq!(
        verify_image(&image, Algorithm::LmsHss, &public_key, &digest),
        Ok(())
    );
}

/// A sub-object of a manifest entry (`"name": { ... }`), brace-matched.
fn object<'a>(entry: &'a str, name: &str) -> &'a str {
    let start = entry
        .find(&format!("\"{name}\": {{"))
        .unwrap_or_else(|| panic!("no object `{name}`"));
    let body = &entry[start..];
    let end = body.find('}').unwrap();
    &body[..=end]
}

fn lens(text: &str) -> Vec<usize> {
    text.split_whitespace()
        .map(|s| s.parse().unwrap())
        .collect()
}

#[test]
fn golden_images_match_manifest() {
    let mut parsed = 0;
    for name in GOLDEN {
        let data = read(name);
        let entry = manifest_entry(name);
        assert_eq!(data.len().to_string(), field(&entry, "bytes"), "{name}");
        assert_eq!(hex(&field(&entry, "sha256")), sha256(&data), "{name}");
        let little = field(&entry, "endian") == "little";
        assert_eq!(
            field(&entry, "imgtool_verify"),
            little.to_string(),
            "{name}"
        );
        match field(&entry, "expect_parse").as_str() {
            "BadMagic" => {
                assert!(!little && name.starts_with("rejected/"), "{name}");
                assert_eq!(Image::parse(&data), Err(ParseError::BadMagic), "{name}");
                continue;
            }
            "Ok" => assert!(little && !name.starts_with("rejected/"), "{name}"),
            other => panic!("{name}: unexpected expect_parse {other}"),
        }
        let image = Image::parse(&data).unwrap_or_else(|e| panic!("{name}: {e}"));
        let header = object(&entry, "header");
        let h = *image.header();
        assert_eq!(h.hdr_size.to_string(), field(header, "hdr_size"), "{name}");
        assert_eq!(
            h.protect_tlv_size.to_string(),
            field(header, "protect_tlv_size"),
            "{name}"
        );
        assert_eq!(h.img_size.to_string(), field(header, "img_size"), "{name}");
        assert_eq!(h.flags.0.to_string(), field(header, "flags"), "{name}");
        let v = h.version;
        assert_eq!(
            format!("{}.{}.{}+{}", v.major, v.minor, v.revision, v.build_num),
            field(header, "version"),
            "{name}"
        );

        for (area, tlvs) in [
            ("protected", protected(&image)),
            ("unprotected", unprotected(&image)),
        ] {
            let kinds: Vec<u16> = tlvs.iter().map(|(k, _)| *k).collect();
            let sizes: Vec<usize> = tlvs.iter().map(|(_, v)| v.len()).collect();
            assert_eq!(
                kinds,
                tlv_list(&field(&entry, &format!("{area}_tlvs"))),
                "{name}"
            );
            assert_eq!(
                sizes,
                lens(&field(&entry, &format!("{area}_tlv_lens"))),
                "{name}"
            );
        }
        assert_eq!(
            image.tlv_end().to_string(),
            field(&entry, "tlv_end"),
            "{name}"
        );
        assert!(image.tlv_end() as usize <= data.len(), "{name}");

        let digest = sha256(signed(&data, &image));
        assert_eq!(digest.to_vec(), hex(&field(&entry, "digest_hex")), "{name}");
        let tlvs = unprotected(&image);
        let value = |kind: u16| tlvs.iter().find(|(k, _)| *k == kind).unwrap().1;
        assert_eq!(value(TLV_SHA256), digest.as_slice(), "{name}");
        assert_eq!(
            value(TLV_KEYHASH),
            hex(&field(&entry, "keyhash_hex")),
            "{name}"
        );
        let sig_type = tlv_list(&field(&entry, "signature_tlv"))[0];
        assert_eq!(
            value(sig_type).len().to_string(),
            field(&entry, "signature_len"),
            "{name}"
        );
        parsed += 1;
    }
    assert_eq!(parsed, 4, "four little-endian golden images parse");
}
