//! ML-DSA-44/65 keelsign images through `keelsign_verify::verify` (SHA-44): the positive
//! fixture per parameter set (TP1), the negatives (TP2), the stripped hybrid (TP3), the
//! error variant of each failure (AC3), and a byte-for-byte check of every committed
//! ML-DSA key and signature against RustCrypto `ml-dsa`'s deterministic signer.
//!
//! The fixtures are generated by `scripts/gen_image_fixtures.py` with the independent
//! signer dilithium-py (pure ML-DSA, deterministic, `MLDSA_CONTEXT`) under two test keys
//! from fixed public seeds (MANIFEST.json `keys`).

// Host test code, not no_std firmware: failing a test with a message is the point.
#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing
)]

use std::fs;
use std::path::PathBuf;

use keelsign_verify::{
    Algorithm, DEFAULT_CHUNK_LEN, Ed25519Error, Ed25519Key, Error, ImageError, Policy, TrustedKey,
    TrustedKeys, VerifiedImage, verify,
};

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tests/fixtures/images")
}

fn read(rel: &str) -> Vec<u8> {
    let path = fixture_dir().join(rel);
    fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

fn manifest() -> String {
    String::from_utf8(read("MANIFEST.json")).unwrap()
}

/// The brace-matched JSON object after `"name": ` (the manifest has no braces in strings).
fn object(text: &str, name: &str) -> String {
    let start = text
        .find(&format!("\"{name}\": {{"))
        .unwrap_or_else(|| panic!("MANIFEST.json has no object `{name}`"));
    let body = &text[start..];
    let open = body.find('{').unwrap();
    let mut depth = 0;
    for (i, c) in body[open..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return body[open..=open + i].to_owned();
                }
            }
            _ => {}
        }
    }
    panic!("unterminated object `{name}`");
}

/// A scalar field of a manifest object, without quotes.
fn field(entry: &str, name: &str) -> Option<String> {
    let needle = format!("\"{name}\": ");
    let start = entry.find(&needle)? + needle.len();
    let rest = &entry[start..];
    let end = rest.find([',', '\n']).unwrap_or(rest.len());
    Some(rest[..end].trim().trim_matches('"').to_owned())
}

fn hex(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).unwrap())
        .collect()
}

fn algorithm(name: &str) -> Algorithm {
    match name {
        "LmsHss" => Algorithm::LmsHss,
        "MlDsa44" => Algorithm::MlDsa44,
        "MlDsa65" => Algorithm::MlDsa65,
        other => panic!("unknown algorithm {other}"),
    }
}

/// The raw Ed25519 test key: the last 32 bytes of its SubjectPublicKeyInfo.
fn ed25519_test_key() -> &'static [u8; 32] {
    let spki = read("keys/ed25519-test-key.spki.der");
    Box::leak(Box::new(spki[12..].try_into().unwrap()))
}

/// The trusted keys of a fixture: its own PQ key (from the manifest) and the Ed25519
/// test key.
fn keys_for(name: &str) -> TrustedKeys<'static, 2, 1> {
    let entry = object(&object(&manifest(), "outputs"), name);
    let pk: &'static [u8] =
        Box::leak(hex(&field(&entry, "public_key_hex").unwrap()).into_boxed_slice());
    let alg = algorithm(&field(&entry, "algorithm").unwrap());
    TrustedKeys::with_ed25519(
        &[TrustedKey {
            algorithm: alg,
            public_key: pk,
        }],
        &[Ed25519Key {
            public_key: ed25519_test_key(),
        }],
    )
    .unwrap()
}

/// `verify` of a committed fixture with its own keys, a 4 KiB TLV buffer and a 256-byte
/// chunk.
fn run(name: &str, policy: Policy) -> Result<VerifiedImage<'static>, Error> {
    run_bytes(&read(name), &keys_for(name), policy)
}

fn run_bytes(
    data: &[u8],
    keys: &TrustedKeys<'static, 2, 1>,
    policy: Policy,
) -> Result<VerifiedImage<'static>, Error> {
    let mut reader = data;
    let mut tlv_buf = [0u8; 4096];
    let mut chunk = [0u8; DEFAULT_CHUNK_LEN];
    verify(&mut reader, keys, policy, &mut tlv_buf, &mut chunk)
}

/// The valid ML-DSA images, the parameter set and the policy that needs the PQ half only
/// (or both halves for the hybrid image).
#[cfg(feature = "ml-dsa")]
const VALID: [(&str, Algorithm, Policy); 5] = [
    ("keelsign-mldsa44.bin", Algorithm::MlDsa44, Policy::PqOnly),
    ("keelsign-mldsa65.bin", Algorithm::MlDsa65, Policy::PqOnly),
    (
        "keelsign-mldsa44-protected-tlvs.bin",
        Algorithm::MlDsa44,
        Policy::PqOnly,
    ),
    (
        "keelsign-mldsa65-protected-tlvs.bin",
        Algorithm::MlDsa65,
        Policy::PqOnly,
    ),
    (
        "keelsign-hybrid-ed25519-mldsa44.bin",
        Algorithm::MlDsa44,
        Policy::Hybrid,
    ),
];

#[cfg(feature = "ml-dsa")]
#[test]
fn mldsa_fixtures_verify_per_parameter_set() {
    let mut per_set = [0usize; 2];
    for (name, alg, policy) in VALID {
        let entry = object(&object(&manifest(), "outputs"), name);
        assert_eq!(
            field(&entry, "verifiable").as_deref(),
            Some("true"),
            "{name}"
        );
        // PqOnly verifies every image, Hybrid the hybrid one (it needs `ed25519`).
        for policy in [Policy::PqOnly, policy] {
            if policy.requires_ed25519() && !keelsign_verify::ed25519::is_enabled() {
                assert_eq!(
                    run(name, policy).map(|_| ()),
                    Err(Error::Ed25519(Ed25519Error::NotEnabled))
                );
                continue;
            }
            let verified = run(name, policy).unwrap_or_else(|e| panic!("{name} {policy:?}: {e:?}"));
            let pq_key = verified.pq_key.unwrap();
            assert_eq!(pq_key.algorithm, alg, "{name}");
            assert_eq!(
                pq_key.public_key,
                hex(&field(&entry, "public_key_hex").unwrap()),
                "{name}"
            );
            assert_eq!(
                verified.digest.to_vec(),
                hex(&field(&entry, "digest_hex").unwrap()),
                "{name}"
            );
        }
        per_set[usize::from(alg == Algorithm::MlDsa65)] += 1;
    }
    assert_eq!(per_set, [3, 2]);
}

/// The ML-DSA test keys (seed, public key) from MANIFEST.json `keys`.
#[cfg(feature = "ml-dsa")]
fn test_key(kind: &str) -> (Vec<u8>, Vec<u8>) {
    let key = object(
        &object(&manifest(), "keys"),
        &format!("mldsa-test-key:{kind}"),
    );
    (
        hex(&field(&key, "seed_hex").unwrap()),
        hex(&field(&key, "public_key_hex").unwrap()),
    )
}

#[cfg(feature = "ml-dsa")]
#[test]
fn fixture_signatures_match_ml_dsa_deterministic_signing() {
    use keelsign_verify::image::Image;
    use keelsign_verify::tlv::{MLDSA_CONTEXT, TLV_MLDSA44_SIG, TLV_MLDSA65_SIG};
    use ml_dsa::{MlDsa44, MlDsa65, MlDsaParams, Seed, SigningKey};
    use sha2::Digest;

    /// RustCrypto's public key and deterministic signature over `m` for `seed`.
    fn rust_crypto<P: MlDsaParams>(seed: &[u8], m: &[u8]) -> (Vec<u8>, Vec<u8>) {
        let sk = SigningKey::<P>::from_seed(&Seed::try_from(seed).unwrap());
        let sig = sk
            .expanded_key()
            .sign_deterministic(m, MLDSA_CONTEXT)
            .unwrap()
            .encode();
        (
            sk.expanded_key().verifying_key().encode().to_vec(),
            sig.to_vec(),
        )
    }

    let manifest = manifest();
    let outputs = object(&manifest, "outputs");
    let mut checked = 0;
    for (kind, tlv, label) in [
        ("mldsa44", TLV_MLDSA44_SIG, "MlDsa44"),
        ("mldsa65", TLV_MLDSA65_SIG, "MlDsa65"),
    ] {
        let (seed, pk) = test_key(kind);
        let key = object(
            &object(&manifest, "keys"),
            &format!("mldsa-test-key:{kind}"),
        );
        let seed_label = field(&key, "seed_label").unwrap();
        assert_eq!(
            seed,
            sha2::Sha256::digest(seed_label.as_bytes()).to_vec(),
            "{kind}: seed is SHA-256 of its label"
        );
        // Every signed (not mutated) image carrying a signature of this set.
        for name in [
            "keelsign-mldsa44.bin",
            "keelsign-mldsa65.bin",
            "keelsign-mldsa44-protected-tlvs.bin",
            "keelsign-mldsa65-protected-tlvs.bin",
            "keelsign-hybrid-ed25519-mldsa44.bin",
            "keelsign-dual-pq-invalid.bin",
        ] {
            let data = read(name);
            let image = Image::parse(&data).unwrap();
            let Some((_, sig)) = image.unprotected().pairs().find(|(t, _)| *t == tlv) else {
                continue;
            };
            let entry = object(&outputs, name);
            let m = hex(&field(&entry, "digest_hex").unwrap());
            let (rc_pk, rc_sig) = match kind {
                "mldsa44" => rust_crypto::<MlDsa44>(&seed, &m),
                _ => rust_crypto::<MlDsa65>(&seed, &m),
            };
            assert_eq!(rc_pk, pk, "{kind}: manifest public key");
            if field(&entry, "algorithm").as_deref() == Some(label) {
                assert_eq!(
                    hex(&field(&entry, "public_key_hex").unwrap()),
                    pk,
                    "{name}: the {kind} test key"
                );
            }
            assert_eq!(
                rc_sig, sig,
                "{name}: dilithium-py and RustCrypto signatures differ"
            );
            checked += 1;
        }
    }
    // 44: mldsa44, -protected-tlvs, hybrid, dual; 65: mldsa65, -protected-tlvs.
    assert_eq!(checked, 6);
}

/// TP2 fixtures #3-#17: (image, its parameter set, the PqOnly verdict with `ml-dsa` on).
const NEGATIVES: [(&str, Algorithm, Error); 15] = [
    // Tampered body: the image rule catches it before any signature...
    (
        "keelsign-mldsa44-bad-body.bin",
        Algorithm::MlDsa44,
        Error::Image(ImageError::DigestMismatch),
    ),
    // ...and with the SHA256 TLV recomputed, the signature does not cover the new M.
    (
        "keelsign-mldsa44-bad-body-rehashed.bin",
        Algorithm::MlDsa44,
        Error::SignatureInvalid,
    ),
    (
        "keelsign-mldsa65-bad-body-rehashed.bin",
        Algorithm::MlDsa65,
        Error::SignatureInvalid,
    ),
    // Tampered protected TLV.
    (
        "keelsign-mldsa44-bad-protected.bin",
        Algorithm::MlDsa44,
        Error::Image(ImageError::DigestMismatch),
    ),
    (
        "keelsign-mldsa44-bad-protected-rehashed.bin",
        Algorithm::MlDsa44,
        Error::SignatureInvalid,
    ),
    (
        "keelsign-mldsa65-bad-protected-rehashed.bin",
        Algorithm::MlDsa65,
        Error::SignatureInvalid,
    ),
    // Tampered unprotected TLVs: the signature (c~), its hint encoding, its length, and
    // the key ID.
    (
        "keelsign-mldsa44-bad-sig.bin",
        Algorithm::MlDsa44,
        Error::SignatureInvalid,
    ),
    (
        "keelsign-mldsa65-bad-sig.bin",
        Algorithm::MlDsa65,
        Error::SignatureInvalid,
    ),
    (
        "keelsign-mldsa44-bad-hint.bin",
        Algorithm::MlDsa44,
        Error::MalformedSignature,
    ),
    (
        "keelsign-mldsa65-bad-hint.bin",
        Algorithm::MlDsa65,
        Error::MalformedSignature,
    ),
    (
        "keelsign-mldsa44-short-sig.bin",
        Algorithm::MlDsa44,
        Error::MalformedSignature,
    ),
    (
        "keelsign-mldsa65-short-sig.bin",
        Algorithm::MlDsa65,
        Error::MalformedSignature,
    ),
    (
        "keelsign-mldsa44-bad-key-id.bin",
        Algorithm::MlDsa44,
        Error::KeyNotTrusted,
    ),
    // A signature from another image (same key, other M).
    (
        "keelsign-mldsa44-foreign-sig.bin",
        Algorithm::MlDsa44,
        Error::SignatureInvalid,
    ),
    (
        "keelsign-mldsa65-foreign-sig.bin",
        Algorithm::MlDsa65,
        Error::SignatureInvalid,
    ),
];

/// Run every TP2 negative under `PqOnly` and assert the verdict `want(algorithm,
/// verdict_with_ml_dsa)`; also check each entry's manifest algorithm and that every class
/// of mutation is present. Returns the `derived_from` base image of each negative.
fn assert_negatives(want: fn(Algorithm, Error) -> Error) -> Vec<String> {
    let manifest = manifest();
    let outputs = object(&manifest, "outputs");
    let mut bases = Vec::new();
    for (name, alg, on) in NEGATIVES {
        let entry = object(&outputs, name);
        assert_eq!(
            field(&entry, "algorithm").map(|a| algorithm(&a)),
            Some(alg),
            "{name}"
        );
        assert_eq!(
            run(name, Policy::PqOnly).map(|_| ()),
            Err(want(alg, on)),
            "{name}"
        );
        bases.push(field(&entry, "derived_from").unwrap());
    }
    assert_eq!(bases.len(), 15);
    // Each class is present: body, protected TLV, unprotected TLV, other image.
    for needle in ["bad-body", "bad-protected", "bad-sig", "foreign-sig"] {
        assert!(
            NEGATIVES.iter().any(|(n, ..)| n.contains(needle)),
            "{needle}"
        );
    }
    bases
}

/// With `ml-dsa`: each negative returns its own variant, and its base image (same keys)
/// verifies, so the mutation alone is the cause.
#[cfg(feature = "ml-dsa")]
#[test]
fn tp2_negatives_return_their_own_variant() {
    for base in assert_negatives(|_, on| on) {
        assert!(run(&base, Policy::PqOnly).is_ok(), "base {base}");
    }
}

/// Without `ml-dsa`: the image rules and the key lookup still come first (their verdicts
/// are unchanged); every other negative is the dispatcher's `UnsupportedAlgorithm` of
/// its parameter set (the manifest's `policy_without_ml_dsa`).
#[cfg(not(feature = "ml-dsa"))]
#[test]
fn tp2_negatives_without_ml_dsa_are_unsupported_algorithm_after_image_rules_and_key_lookup() {
    assert_negatives(|alg, on| match on {
        Error::Image(_) | Error::KeyNotTrusted => on,
        _ => Error::UnsupportedAlgorithm(alg),
    });
}

#[cfg(feature = "ml-dsa")]
#[test]
fn sampled_signature_byte_flips_never_verify() {
    use keelsign_verify::image::Image;

    for (name, alg) in [
        ("keelsign-mldsa44.bin", Algorithm::MlDsa44),
        ("keelsign-mldsa65.bin", Algorithm::MlDsa65),
    ] {
        let base = read(name);
        let keys = keys_for(name);
        let range = {
            let image = Image::parse(&base).unwrap();
            let sig = image
                .unprotected()
                .pairs()
                .find(|(t, _)| *t == alg.tlv_type())
                .unwrap()
                .1;
            let start = sig.as_ptr() as usize - base.as_ptr() as usize;
            start..start + sig.len()
        };
        assert!(run_bytes(&base, &keys, Policy::PqOnly).is_ok(), "{name}");
        // 64 positions spread over c~, z and the hints, plus the last byte.
        let step = range.len() / 63;
        let positions: Vec<usize> = range
            .clone()
            .step_by(step)
            .take(63)
            .chain([range.end - 1])
            .collect();
        assert_eq!(positions.len(), 64);
        for at in positions {
            let mut d = base.clone();
            d[at] ^= 0x01;
            let result = run_bytes(&d, &keys, Policy::PqOnly).map(|_| ());
            assert!(
                matches!(
                    result,
                    Err(Error::SignatureInvalid | Error::MalformedSignature)
                ),
                "{name} byte {}: {result:?}",
                at - range.start
            );
        }
    }
}

#[test]
fn tp3_stripping_the_pq_tlv_from_a_hybrid_mldsa_image_fails_when_pq_required() {
    let ed25519_on = keelsign_verify::ed25519::is_enabled();
    for name in [
        "keelsign-hybrid-mldsa44-missing-pq.bin",
        "keelsign-hybrid-mldsa44-stripped-pq.bin",
    ] {
        let entry = object(&object(&manifest(), "outputs"), name);
        assert_eq!(
            field(&entry, "derived_from").as_deref(),
            Some("keelsign-hybrid-ed25519-mldsa44.bin")
        );
        // PqOnly needs the PQ half: it is gone, whatever the features.
        assert_eq!(
            run(name, Policy::PqOnly).map(|_| ()),
            Err(Error::MissingPqSignature),
            "{name}"
        );
        if ed25519_on {
            assert_eq!(
                run(name, Policy::Hybrid).map(|_| ()),
                Err(Error::MissingPqSignature),
                "{name}"
            );
            // The classical half alone still verifies under ClassicalOnly.
            assert!(run(name, Policy::ClassicalOnly).is_ok(), "{name}");
        } else {
            for policy in [Policy::Hybrid, Policy::ClassicalOnly] {
                assert_eq!(
                    run(name, policy).map(|_| ()),
                    Err(Error::Ed25519(Ed25519Error::NotEnabled)),
                    "{name}"
                );
            }
        }
    }
}

#[cfg(not(feature = "ml-dsa"))]
#[test]
fn without_ml_dsa_every_mldsa_row_fails_closed() {
    let manifest = manifest();
    let outputs = object(&manifest, "outputs");
    let names: Vec<String> = outputs
        .lines()
        .filter_map(|line| {
            line.strip_prefix("    \"")
                .and_then(|rest| rest.strip_suffix("\": {"))
                .map(str::to_owned)
        })
        .collect();
    let mut rows = 0;
    for name in &names {
        let entry = object(&outputs, name);
        let alg = match field(&entry, "algorithm").as_deref() {
            Some("MlDsa44") => Algorithm::MlDsa44,
            Some("MlDsa65") => Algorithm::MlDsa65,
            _ => continue,
        };
        rows += 1;
        for policy in [Policy::PqOnly, Policy::Hybrid] {
            let result = run(name, policy).map(|_| ());
            assert!(result.is_err(), "{name} {policy:?} verified without ml-dsa");
            if result == Err(Error::UnsupportedAlgorithm(alg)) {
                continue;
            }
            // Anything else fails before the ML-DSA backend would have run.
            assert!(
                matches!(
                    result,
                    Err(Error::Image(_)
                        | Error::Ed25519(_)
                        | Error::KeyNotTrusted
                        | Error::MissingPqSignature
                        | Error::MultiplePqSignatures)
                ),
                "{name} {policy:?}: {result:?}"
            );
        }
    }
    // 4 valid + the hybrid, 15 negatives and 2 stripped hybrids (the dual-PQ image's
    // key is LMS).
    assert_eq!(rows, 22);
}
