//! The SHA-46 policy matrix: every image in `tests/fixtures/images/MANIFEST.json`
//! (generated by `scripts/gen_image_fixtures.py`) under every `Policy`, through the single
//! entry point `keelsign_verify::verify`, against the `policy` cells the manifest records
//! (the same cells docs/policy.md's matrix and `policy-matrix.bin` carry).
//!
//! The trusted keys of every image are its own post-quantum key (if the manifest has one)
//! and the Ed25519 test key (`keys/ed25519-test-key.spki.der`). The manifest cells assume
//! the `ed25519` and `ml-dsa` features; without `ed25519`, `ClassicalOnly` and `Hybrid`
//! must be `Ed25519(NotEnabled)` everywhere, and without `ml-dsa` the cells are the
//! entry's `policy_without_ml_dsa` object where it has one (SHA-44).

// Host test code, not no_std firmware: failing a test with a message is the point.
#![allow(
    clippy::panic,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing
)]

use std::fs;
use std::path::PathBuf;

use embedded_storage::nor_flash::{ErrorType, NorFlashErrorKind, ReadNorFlash};
use keelsign_verify::{
    Algorithm, DEFAULT_CHUNK_LEN, Ed25519Key, Error, ImageError, NorFlashReader, Policy,
    TrustedKey, TrustedKeys, VerifiedImage, verify,
};

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../tests/fixtures/images")
}

fn read(rel: &str) -> Vec<u8> {
    let path = fixture_dir().join(rel);
    fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

fn manifest() -> String {
    String::from_utf8(read("MANIFEST.json")).unwrap()
}

/// The names of every output in MANIFEST.json (the keys of `outputs`, written by
/// `json.dumps(indent=2)` at four spaces).
fn output_names(manifest: &str) -> Vec<String> {
    let outputs = &manifest[manifest.find("\n  \"outputs\": {").unwrap()..];
    let outputs = &outputs[..outputs.find("\n  },").unwrap_or(outputs.len())];
    outputs
        .lines()
        .filter_map(|line| {
            line.strip_prefix("    \"")
                .and_then(|rest| rest.strip_suffix("\": {"))
                .map(str::to_owned)
        })
        .collect()
}

/// A fixture's entry in MANIFEST.json (brace-matched; the manifest has no braces in
/// strings).
fn entry(manifest: &str, name: &str) -> String {
    let start = manifest
        .find(&format!("\n    \"{name}\": {{"))
        .unwrap_or_else(|| panic!("MANIFEST.json has no entry `{name}`"));
    let body = &manifest[start..];
    let open = body.find('{').unwrap();
    let mut depth = 0;
    for (i, c) in body[open..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    return body[open..=open + i].to_owned();
                }
            }
            _ => {}
        }
    }
    panic!("unterminated entry `{name}`");
}

/// A scalar field of a manifest entry, without quotes.
fn field(entry: &str, name: &str) -> Option<String> {
    let needle = format!("\"{name}\": ");
    let start = entry.find(&needle)? + needle.len();
    let rest = &entry[start..];
    let end = rest.find([',', '\n']).unwrap_or(rest.len());
    Some(rest[..end].trim().trim_matches('"').to_owned())
}

fn hex(text: &str) -> Vec<u8> {
    (0..text.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&text[i..i + 2], 16).unwrap())
        .collect()
}

fn policy_key(policy: Policy) -> &'static str {
    match policy {
        Policy::ClassicalOnly => "classical_only",
        Policy::PqOnly => "pq_only",
        Policy::Hybrid => "hybrid",
        other => panic!("unknown policy {other:?}"),
    }
}

/// The manifest cell of `policy` (the `ml-dsa`-on cell).
fn cell(entry: &str, policy: Policy) -> String {
    let policy_object = &entry[entry.find("\"policy\": {").expect("policy object")..];
    field(policy_object, policy_key(policy)).unwrap()
}

/// The manifest cell of `policy` without the `ml-dsa` feature: the
/// `policy_without_ml_dsa` object's, where the entry has one, else [`cell`].
fn cell_without_ml_dsa(entry: &str, policy: Policy) -> String {
    match entry.find("\"policy_without_ml_dsa\": {") {
        Some(at) => field(&entry[at..], policy_key(policy)).unwrap(),
        None => cell(entry, policy),
    }
}

/// The verdict string the manifest uses: `Ok`, or the error as Debug prints it, with a
/// TLV type as `0x%04X`.
fn verdict(result: &Result<VerifiedImage<'_>, Error>) -> String {
    match result {
        Ok(_) => "Ok".to_owned(),
        Err(Error::Image(ImageError::KeelsignTlvProtected(t))) => {
            format!("Image(KeelsignTlvProtected(0x{t:04X}))")
        }
        Err(e) => format!("{e:?}"),
    }
}

/// The raw Ed25519 test key: the last 32 bytes of its SubjectPublicKeyInfo.
fn ed25519_test_key() -> &'static [u8; 32] {
    let spki = read("keys/ed25519-test-key.spki.der");
    assert_eq!(spki.len(), 44);
    Box::leak(Box::new(spki[12..].try_into().unwrap()))
}

fn algorithm(name: &str) -> Algorithm {
    match name {
        "LmsHss" => Algorithm::LmsHss,
        "MlDsa44" => Algorithm::MlDsa44,
        "MlDsa65" => Algorithm::MlDsa65,
        other => panic!("unknown algorithm {other}"),
    }
}

/// The trusted keys of an image: its own PQ key, if any, and the Ed25519 test key.
fn keys_for(entry: &str) -> TrustedKeys<'static, 2, 1> {
    let ed = [Ed25519Key {
        public_key: ed25519_test_key(),
    }];
    match field(entry, "public_key_hex") {
        Some(pk) => {
            let pk: &'static [u8] = Box::leak(hex(&pk).into_boxed_slice());
            let alg = algorithm(&field(entry, "algorithm").unwrap());
            TrustedKeys::with_ed25519(
                &[TrustedKey {
                    algorithm: alg,
                    public_key: pk,
                }],
                &ed,
            )
            .unwrap()
        }
        None => TrustedKeys::with_ed25519(&[], &ed).unwrap(),
    }
}

fn run<'k, const N: usize, const E: usize>(
    data: &[u8],
    keys: &TrustedKeys<'k, N, E>,
    policy: Policy,
) -> Result<VerifiedImage<'k>, Error> {
    let mut reader = data;
    let mut tlv_buf = [0u8; 4096];
    let mut chunk = [0u8; DEFAULT_CHUNK_LEN];
    verify(&mut reader, keys, policy, &mut tlv_buf, &mut chunk)
}

fn ed25519_on() -> bool {
    keelsign_verify::ed25519::is_enabled()
}

fn ml_dsa_on() -> bool {
    keelsign_verify::mldsa::is_enabled()
}

/// The expected verdict of a cell in this build: the manifest's (the
/// `policy_without_ml_dsa` cell without the `ml-dsa` feature), or `NotEnabled` for a
/// policy needing the `ed25519` feature when it is off.
fn expected(entry: &str, policy: Policy) -> String {
    if policy.requires_ed25519() && !ed25519_on() {
        "Ed25519(NotEnabled)".to_owned()
    } else if ml_dsa_on() {
        cell(entry, policy)
    } else {
        cell_without_ml_dsa(entry, policy)
    }
}

#[test]
fn every_manifest_image_matches_its_policy_cells() {
    let manifest = manifest();
    let names = output_names(&manifest);
    assert_eq!(names.len(), 58, "{names:?}");
    // TP1's six rows are in the matrix.
    for name in [
        "mcuboot-ed25519.bin",
        "keelsign-lms-m32-h5.bin",
        "keelsign-hybrid-ed25519-lms.bin",
        "keelsign-hybrid-bad-ed25519.bin",
        "keelsign-hybrid-bad-pq.bin",
        "keelsign-hybrid-missing-pq.bin",
        // SHA-44's ML-DSA rows.
        "keelsign-mldsa44.bin",
        "keelsign-mldsa65.bin",
        "keelsign-hybrid-ed25519-mldsa44.bin",
        "keelsign-mldsa44-foreign-sig.bin",
        "keelsign-hybrid-mldsa44-stripped-pq.bin",
    ] {
        assert!(names.iter().any(|n| n == name), "{name} missing");
    }
    let mut cells = 0;
    for name in &names {
        let entry = entry(&manifest, name);
        let data = read(name);
        let keys = keys_for(&entry);
        for &policy in Policy::ALL {
            let got = verdict(&run(&data, &keys, policy));
            assert_eq!(got, expected(&entry, policy), "{name} under {policy:?}");
            cells += 1;
        }
    }
    assert_eq!(cells, 58 * 3);
}

/// SHA-69 AC2 / TP2: the table-driven matrix has LMS-only, hybrid Ed25519 + LMS (L=1),
/// hybrid Ed25519 + HSS (L=2) and hybrid Ed25519 + ML-DSA rows, the HSS-2 hybrid rows
/// with either half tampered or missing, and each row gives its recorded cells in this
/// build.
#[test]
fn matrix_has_lms_only_hybrid_lms_hybrid_hss2_and_hybrid_mldsa_rows() {
    let manifest = manifest();
    let names = output_names(&manifest);
    let ok = ("Ok", "Ok", "Ok");
    let rows: [(&str, (&str, &str, &str)); 8] = [
        (
            "keelsign-lms-m32-h5.bin",
            ("Ed25519(Missing)", "Ok", "Ed25519(Missing)"),
        ),
        ("keelsign-hybrid-ed25519-lms.bin", ok),
        ("keelsign-hybrid-ed25519-hss2.bin", ok),
        ("keelsign-hybrid-ed25519-mldsa44.bin", ok),
        (
            "keelsign-hybrid-hss2-bad-ed25519.bin",
            (
                "Ed25519(SignatureInvalid)",
                "Ok",
                "Ed25519(SignatureInvalid)",
            ),
        ),
        (
            "keelsign-hybrid-hss2-bad-pq.bin",
            ("Ok", "SignatureInvalid", "SignatureInvalid"),
        ),
        (
            "keelsign-hybrid-hss2-bad-top-level.bin",
            ("Ok", "SignatureInvalid", "SignatureInvalid"),
        ),
        (
            "keelsign-hybrid-hss2-missing-pq.bin",
            ("Ok", "MissingPqSignature", "MissingPqSignature"),
        ),
    ];
    for (name, (classical_only, pq_only, hybrid)) in rows {
        assert!(names.iter().any(|n| n == name), "{name} missing");
        let entry = entry(&manifest, name);
        assert_eq!(
            [
                cell(&entry, Policy::ClassicalOnly),
                cell(&entry, Policy::PqOnly),
                cell(&entry, Policy::Hybrid),
            ],
            [classical_only, pq_only, hybrid],
            "{name}"
        );
        let data = read(name);
        let keys = keys_for(&entry);
        for &policy in Policy::ALL {
            let got = verdict(&run(&data, &keys, policy));
            assert_eq!(got, expected(&entry, policy), "{name} under {policy:?}");
        }
    }
    // The HSS-2 hybrid image is a two-level key with an Ed25519 pair.
    let hss2 = entry(&manifest, "keelsign-hybrid-ed25519-hss2.bin");
    assert_eq!(field(&hss2, "algorithm").unwrap(), "LmsHss");
    assert_eq!(field(&hss2, "ed25519").unwrap(), "true");
    assert!(
        field(&hss2, "public_key_hex")
            .unwrap()
            .starts_with("00000002")
    );
}

#[test]
fn nor_flash_reader_at_an_offset_gives_the_same_verdicts() {
    /// An in-memory NOR flash (READ_SIZE 1), as on the boards.
    struct Flash(Vec<u8>);
    impl ErrorType for Flash {
        type Error = NorFlashErrorKind;
    }
    impl ReadNorFlash for Flash {
        const READ_SIZE: usize = 1;
        fn read(&mut self, offset: u32, bytes: &mut [u8]) -> Result<(), Self::Error> {
            let start = offset as usize;
            let src = self
                .0
                .get(start..start + bytes.len())
                .ok_or(NorFlashErrorKind::OutOfBounds)?;
            bytes.copy_from_slice(src);
            Ok(())
        }
        fn capacity(&self) -> usize {
            self.0.len()
        }
    }

    let manifest = manifest();
    let names = output_names(&manifest);
    // Every image back to back in one flash, each at its own offset, as policy-kat
    // reads them from `.rodata` on the boards; erased (0xFF) bytes between them.
    let mut flash = vec![0xFF; 0x1000];
    let mut slots = Vec::new();
    for name in &names {
        let data = read(name);
        let base = flash.len();
        flash.extend_from_slice(&data);
        flash.extend_from_slice(&[0xFF; 61]);
        slots.push((name, base, data));
    }
    let mut flash = Flash(flash);
    for (name, base, data) in &slots {
        let entry = entry(&manifest, name);
        let keys = keys_for(&entry);
        for &policy in Policy::ALL {
            let len = u32::try_from(data.len()).unwrap();
            let mut reader = NorFlashReader::new(&mut flash, *base as u32, len).unwrap();
            let mut tlv_buf = [0u8; 4096];
            let mut chunk = [0u8; DEFAULT_CHUNK_LEN];
            let from_flash = verify(&mut reader, &keys, policy, &mut tlv_buf, &mut chunk);
            assert_eq!(
                from_flash,
                run(data, &keys, policy),
                "{name} under {policy:?}"
            );
            assert_eq!(verdict(&from_flash), expected(&entry, policy));
        }
    }
}

#[test]
fn verified_image_exposes_version_counter_digest_and_keys() {
    let manifest = manifest();
    let with_counter = [
        "mcuboot-ed25519.bin",
        "mcuboot-ed25519-padded.bin",
        "mcuboot-ed25519-200k.bin",
        "keelsign-lms-protected-tlvs.bin",
        "keelsign-hybrid-protected-tlvs.bin",
        "keelsign-mldsa44-protected-tlvs.bin",
        "keelsign-mldsa65-protected-tlvs.bin",
    ];
    let ed = ed25519_test_key();
    let mut ok = 0;
    let mut counters = 0;
    for name in output_names(&manifest) {
        let entry = entry(&manifest, &name);
        let data = read(&name);
        let keys = keys_for(&entry);
        for &policy in Policy::ALL {
            let Ok(verified) = run(&data, &keys, policy) else {
                continue;
            };
            ok += 1;
            assert_eq!(verified.policy, policy);
            let v = verified.version;
            assert_eq!(
                (v.major, v.minor, v.revision, v.build_num),
                (1, 2, 3, 4),
                "{name}"
            );
            let counter = with_counter.contains(&name.as_str());
            assert_eq!(
                verified.security_counter,
                counter.then_some(7),
                "{name} {policy:?}"
            );
            counters += usize::from(counter);
            assert_eq!(
                verified.digest.to_vec(),
                hex(&field(&entry, "digest_hex").unwrap()),
                "{name}"
            );
            assert_eq!(
                verified.image_len.to_string(),
                field(&entry, "tlv_end").unwrap(),
                "{name}"
            );
            assert_eq!(
                verified.pq_key.is_some(),
                policy.requires_pq(),
                "{name} {policy:?}"
            );
            if let Some(key) = verified.pq_key {
                assert_eq!(
                    key.public_key,
                    hex(&field(&entry, "public_key_hex").unwrap())
                );
            }
            assert_eq!(
                verified.ed25519_key,
                policy
                    .requires_ed25519()
                    .then_some(Ed25519Key { public_key: ed }),
                "{name} {policy:?}"
            );
        }
    }
    // Every Ok cell of the manifest was checked.
    let expected_ok: usize = output_names(&manifest)
        .iter()
        .map(|name| {
            let entry = entry(&manifest, name);
            Policy::ALL
                .iter()
                .filter(|&&p| expected(&entry, p) == "Ok")
                .count()
        })
        .sum();
    assert_eq!(ok, expected_ok);
    assert!(ok >= 6, "{ok}");
    assert!(counters >= 1, "{counters}");
}

/// Offsets of the first unprotected TLV value of type `kind` in `data`.
#[cfg(feature = "ed25519")]
fn value_range(data: &[u8], kind: u16) -> std::ops::Range<usize> {
    let image = keelsign_verify::image::Image::parse(data).unwrap();
    let value = image
        .unprotected()
        .pairs()
        .find(|(t, _)| *t == kind)
        .unwrap()
        .1;
    let start = value.as_ptr() as usize - data.as_ptr() as usize;
    start..start + value.len()
}

#[cfg(feature = "ed25519")]
#[test]
fn hybrid_halves_tampered_name_the_half() {
    use keelsign_verify::Ed25519Error;
    use keelsign_verify::image::IMAGE_TLV_ED25519;
    use keelsign_verify::tlv::TLV_LMS_HSS_SIG;

    let manifest = manifest();
    let base_entry = entry(&manifest, "keelsign-hybrid-ed25519-lms.bin");
    let keys = keys_for(&base_entry);
    let base = read("keelsign-hybrid-ed25519-lms.bin");
    for &policy in Policy::ALL {
        assert!(run(&base, &keys, policy).is_ok(), "{policy:?}");
    }
    // The committed tampered images (they share the base's keys).
    assert_eq!(
        run(
            &read("keelsign-hybrid-bad-ed25519.bin"),
            &keys,
            Policy::Hybrid
        )
        .map(|_| ()),
        Err(Error::Ed25519(Ed25519Error::SignatureInvalid))
    );
    assert_eq!(
        run(&read("keelsign-hybrid-bad-pq.bin"), &keys, Policy::Hybrid).map(|_| ()),
        Err(Error::SignatureInvalid)
    );
    // Every byte of the Ed25519 signature flipped: the classical half is named.
    let ed_sig = value_range(&base, IMAGE_TLV_ED25519);
    assert_eq!(ed_sig.len(), 64);
    for at in ed_sig {
        let mut d = base.clone();
        d[at] ^= 0x01;
        let result = run(&d, &keys, Policy::Hybrid);
        assert!(
            matches!(result, Err(Error::Ed25519(_))),
            "ED25519 byte {at}: {result:?}"
        );
    }
    // Sampled bytes of the LMS signature flipped: a PQ-half (flat) variant.
    let lms_sig = value_range(&base, TLV_LMS_HSS_SIG);
    let step = lms_sig.len() / 16;
    let mut sampled = 0;
    for at in lms_sig.clone().step_by(step).take(16) {
        let mut d = base.clone();
        d[at] ^= 0x01;
        let result = run(&d, &keys, Policy::Hybrid);
        assert!(
            matches!(
                result,
                Err(Error::SignatureInvalid | Error::MalformedSignature)
            ),
            "LMS byte {at}: {result:?}"
        );
        sampled += 1;
    }
    assert_eq!(sampled, 16);
    // Dropping either half.
    assert_eq!(
        run(
            &read("keelsign-hybrid-keyhash-only.bin"),
            &keys,
            Policy::Hybrid
        )
        .map(|_| ()),
        Err(Error::Ed25519(Ed25519Error::Missing))
    );
    assert_eq!(
        run(
            &read("keelsign-hybrid-missing-pq.bin"),
            &keys,
            Policy::Hybrid
        )
        .map(|_| ()),
        Err(Error::MissingPqSignature)
    );
}

#[test]
fn ml_dsa_rows_verify_with_the_feature_and_fail_closed_without_it() {
    let manifest = manifest();
    let mut differing = 0;
    for name in output_names(&manifest) {
        let entry = entry(&manifest, &name);
        let alg = match field(&entry, "algorithm").as_deref() {
            Some("MlDsa44") => Algorithm::MlDsa44,
            Some("MlDsa65") => Algorithm::MlDsa65,
            _ => {
                assert!(
                    !entry.contains("\"policy_without_ml_dsa\""),
                    "{name}: only ML-DSA rows depend on the ml-dsa feature"
                );
                continue;
            }
        };
        let data = read(&name);
        let keys = keys_for(&entry);
        for &policy in Policy::ALL {
            let (on, off) = (cell(&entry, policy), cell_without_ml_dsa(&entry, policy));
            if on != off {
                differing += 1;
                // Only a PQ-half cell the ML-DSA backend decides changes, and only to the
                // dispatcher's UnsupportedAlgorithm.
                assert!(policy.requires_pq(), "{name} {policy:?}");
                assert!(
                    ["Ok", "SignatureInvalid", "MalformedSignature"].contains(&on.as_str()),
                    "{name} {policy:?}: {on}"
                );
                assert_eq!(off, format!("UnsupportedAlgorithm({alg:?})"), "{name}");
            }
            if !policy.requires_ed25519() || ed25519_on() {
                let got = verdict(&run(&data, &keys, policy));
                let want = if ml_dsa_on() { on } else { off };
                assert_eq!(got, want, "{name} {policy:?} (ml-dsa {})", ml_dsa_on());
            }
        }
    }
    // 4 PqOnly images + the hybrid (PqOnly and Hybrid) + 12 backend negatives.
    assert_eq!(differing, 4 + 2 + 12);
}

#[cfg(feature = "ed25519")]
#[test]
fn golden_ed25519_images_verify_under_classical_only() {
    use keelsign_verify::Ed25519Error;
    use keelsign_verify::{DefaultBackend, verify_with};

    let manifest = manifest();
    let ed = ed25519_test_key();
    for name in [
        "mcuboot-ed25519.bin",
        "mcuboot-ed25519-padded.bin",
        "mcuboot-ed25519-200k.bin",
    ] {
        let entry = entry(&manifest, name);
        let data = read(name);
        let keys = keys_for(&entry);
        let verified = run(&data, &keys, Policy::ClassicalOnly).unwrap();
        assert_eq!(verified.ed25519_key, Some(Ed25519Key { public_key: ed }));
        assert_eq!(verified.pq_key, None);
        // The chunk size does not matter (the 200 KB body is streamed).
        for chunk_len in [1usize, 64, 4096] {
            let mut reader = data.as_slice();
            let mut chunk = vec![0u8; chunk_len];
            let again = verify_with(
                &DefaultBackend::new(),
                &mut reader,
                &keys,
                Policy::ClassicalOnly,
                &mut [0u8; 4096],
                &mut chunk,
            );
            assert_eq!(again, Ok(verified), "{name} chunk {chunk_len}");
        }
        // Without the test key trusted: KeyNotTrusted, not Missing.
        let no_ed = TrustedKeys::<1, 1>::with_ed25519(&[], &[]).unwrap();
        assert_eq!(
            run(&data, &no_ed, Policy::ClassicalOnly).map(|_| ()),
            Err(Error::Ed25519(Ed25519Error::KeyNotTrusted)),
            "{name}"
        );
        let pq_only_set = TrustedKeys::<1>::new(&[]).unwrap();
        assert_eq!(
            run(&data, &pq_only_set, Policy::ClassicalOnly).map(|_| ()),
            Err(Error::Ed25519(Ed25519Error::KeyNotTrusted)),
            "{name}"
        );
    }
    // RSA and ECDSA goldens carry no Ed25519 pair.
    for name in ["mcuboot-rsa2048.bin", "mcuboot-ecdsa-p256.bin"] {
        let entry = entry(&manifest, name);
        assert_eq!(
            run(&read(name), &keys_for(&entry), Policy::ClassicalOnly).map(|_| ()),
            Err(Error::Ed25519(Ed25519Error::Missing)),
            "{name}"
        );
    }
}
