//! SHA-51: the keelsign CLI's `sign` and `inspect` commands — the CI steps they need, the
//! inspect JSON schema, the inspect snapshot generator and the exit codes in
//! docs/signing.md.

use repo_checks::workspace_root;
use std::fs;

fn read(rel: &str) -> String {
    let path = workspace_root().join(rel);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// The text of the CI job `name` (two-space indented key), up to the next job.
fn ci_job(ci: &str, name: &str) -> String {
    let start = ci
        .find(&format!("\n  {name}:"))
        .unwrap_or_else(|| panic!("ci.yml must have a `{name}` job"));
    ci[start + 1..]
        .lines()
        .enumerate()
        .take_while(|(i, line)| {
            let next_job = line.starts_with("  ") && !line.starts_with("   ");
            let top_level = !line.is_empty() && !line.starts_with(' ');
            *i == 0 || !(next_job || top_level)
        })
        .map(|(_, line)| format!("{line}\n"))
        .collect()
}

/// keelsign enables keelsign-verify's `ml-dsa` feature, so `cargo test --workspace`
/// runs policy-kat with ML-DSA on; the `ci` job runs it alone for the off state.
#[test]
fn ci_runs_policy_kat_with_ml_dsa_off_and_the_imgtool_tests() {
    let ci = read(".github/workflows/ci.yml");
    let host = ci_job(&ci, "ci");
    for needle in [
        "cargo test -p policy-kat --locked\n",
        "cargo test -p policy-kat --locked --features keelsign-verify/ml-dsa",
    ] {
        assert!(host.contains(needle), "ci job must run `{needle}`");
    }
}

/// AC3: the inspect JSON schema is committed, is a Draft 2020-12 schema with
/// `schema_version` 1, and is what keelsign's tests validate against.
#[test]
fn inspect_schema_is_present_and_referenced() {
    let schema = read("docs/inspect-schema.json");
    for needle in [
        "\"$schema\": \"https://json-schema.org/draft/2020-12/schema\"",
        "\"schema_version\": {\n      \"const\": 1\n    }",
        "\"format\": {\n      \"const\": \"keelsign-inspect\"\n    }",
        "\"additionalProperties\": false",
    ] {
        assert!(
            schema.contains(needle),
            "docs/inspect-schema.json lacks `{needle}`"
        );
    }
    let tests = read("keelsign/tests/inspect.rs");
    assert!(tests.contains("docs/inspect-schema.json"));
    assert!(tests.contains("jsonschema::draft202012"));
    let source = read("keelsign/src/inspect.rs");
    assert!(source.contains("pub const SCHEMA_VERSION: u64 = 1;"));
    assert!(source.contains("docs/inspect-schema.json"));
}

/// The inspect snapshots are regenerated by scripts/make-fixtures.sh, after the images
/// they are made from, with a `--keelsign PATH` option so cargo is not nested.
#[test]
fn make_fixtures_runs_inspect_snapshots_after_images() {
    let sh = read("scripts/make-fixtures.sh");
    let images = sh
        .find("run python3 scripts/gen_image_fixtures.py")
        .expect("make-fixtures runs the image generator");
    let snapshots = sh
        .find("run python3 scripts/gen_inspect_snapshots.py")
        .expect("make-fixtures runs the inspect snapshot generator");
    assert!(images < snapshots, "snapshots come after the images");
    assert!(
        sh.contains("--keelsign)"),
        "make-fixtures takes --keelsign PATH"
    );
    assert!(sh.contains("${keelsign[@]+\"${keelsign[@]}\"}"));
    let script = read("scripts/gen_inspect_snapshots.py");
    for needle in [
        "keelsign/tests/snapshots/inspect",
        "--check",
        "--keelsign",
        "\"cargo\", \"run\", \"-q\", \"-p\", \"keelsign\", \"--locked\"",
    ] {
        assert!(
            script.contains(needle),
            "scripts/gen_inspect_snapshots.py lacks `{needle}`"
        );
    }
}
