//! SHA-51: the keelsign CLI's `sign` and `inspect` commands — the CI steps they need, the
//! inspect JSON schema, the inspect snapshot generator and the exit codes in
//! docs/signing.md. SHA-53: `verify`, the final exit codes and the README quickstart.

use repo_checks::workspace_root;
use std::fs;

fn read(rel: &str) -> String {
    let path = workspace_root().join(rel);
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// The text of the CI job `name` (two-space indented key), up to the next job.
fn ci_job(ci: &str, name: &str) -> String {
    let start = ci
        .find(&format!("\n  {name}:"))
        .unwrap_or_else(|| panic!("ci.yml must have a `{name}` job"));
    ci[start + 1..]
        .lines()
        .enumerate()
        .take_while(|(i, line)| {
            let next_job = line.starts_with("  ") && !line.starts_with("   ");
            let top_level = !line.is_empty() && !line.starts_with(' ');
            *i == 0 || !(next_job || top_level)
        })
        .map(|(_, line)| format!("{line}\n"))
        .collect()
}

/// keelsign enables keelsign-verify's `ml-dsa` feature, so `cargo test --workspace`
/// runs policy-kat with ML-DSA on; the `ci` job runs it alone for the off state. The
/// same job installs imgtool 2.4.0 and runs the ignored imgtool interop tests.
#[test]
fn ci_runs_policy_kat_with_ml_dsa_off_and_the_imgtool_tests() {
    let ci = read(".github/workflows/ci.yml");
    let host = ci_job(&ci, "ci");
    for needle in [
        "cargo test -p policy-kat --locked\n",
        "cargo test -p policy-kat --locked --features keelsign-verify/ml-dsa",
        "pip install imgtool==2.4.0",
        "cargo test -p keelsign --locked --test imgtool -- --ignored",
    ] {
        assert!(host.contains(needle), "ci job must run `{needle}`");
    }
}

/// AC3: the inspect JSON schema is committed, is a Draft 2020-12 schema with
/// `schema_version` 1, and is what keelsign's tests validate against.
#[test]
fn inspect_schema_is_present_and_referenced() {
    let schema = read("docs/inspect-schema.json");
    for needle in [
        "\"$schema\": \"https://json-schema.org/draft/2020-12/schema\"",
        "\"schema_version\": {\n      \"const\": 1\n    }",
        "\"format\": {\n      \"const\": \"keelsign-inspect\"\n    }",
        "\"additionalProperties\": false",
    ] {
        assert!(
            schema.contains(needle),
            "docs/inspect-schema.json lacks `{needle}`"
        );
    }
    let tests = read("keelsign/tests/inspect.rs");
    assert!(tests.contains("docs/inspect-schema.json"));
    assert!(tests.contains("jsonschema::draft202012"));
    let source = read("keelsign/src/inspect.rs");
    assert!(source.contains("pub const SCHEMA_VERSION: u64 = 1;"));
    assert!(source.contains("docs/inspect-schema.json"));
    let signing = read("docs/signing.md");
    assert!(
        signing.contains("(inspect-schema.json)"),
        "docs/signing.md links the schema"
    );
}

/// The exit codes `(code, meaning)` of a Markdown table: rows `| N | ... |` (or, with
/// `prefix`, `//! | N | ... |`).
fn exit_code_rows(text: &str, prefix: &str) -> Vec<u8> {
    text.lines()
        .filter_map(|l| l.strip_prefix(prefix))
        .filter_map(|l| l.strip_prefix("| "))
        .filter_map(|l| l.split_once(" |"))
        .filter_map(|(code, _)| code.parse().ok())
        .collect()
}

/// docs/signing.md, docs/keys.md and docs/verify.md list exactly the exit codes
/// keelsign/src/error.rs documents and assigns (0 to 9, final since SHA-53; SHA-67 added
/// 10 and 11 for stateful LMS/HSS keys).
#[test]
fn signing_doc_exit_codes_match_error_rs() {
    let error_rs = read("keelsign/src/error.rs");
    let documented = exit_code_rows(&error_rs, "//! ");
    let expected: Vec<u8> = (0..=11).collect();
    assert_eq!(
        documented, expected,
        "keelsign/src/error.rs exit-code table"
    );
    for code in 1..=11 {
        assert!(
            error_rs.contains(&format!("=> {code},")) || error_rs.contains(&format!("=> {code}\n")),
            "error.rs assigns exit code {code}"
        );
    }
    for doc in ["docs/signing.md", "docs/keys.md", "docs/verify.md"] {
        let text = read(doc);
        let section = text
            .split("\n## Exit codes\n")
            .nth(1)
            .and_then(|rest| rest.split("\n## ").next())
            .unwrap_or_else(|| panic!("{doc} has an `## Exit codes` section"));
        assert_eq!(
            exit_code_rows(section, ""),
            expected,
            "{doc} exit-code table"
        );
    }
}

/// The inspect snapshots are regenerated by scripts/make-fixtures.sh, after the images
/// they are made from, with a `--keelsign PATH` option so cargo is not nested.
#[test]
fn make_fixtures_runs_inspect_snapshots_after_images() {
    let sh = read("scripts/make-fixtures.sh");
    let images = sh
        .find("run python3 scripts/gen_image_fixtures.py")
        .expect("make-fixtures runs the image generator");
    let snapshots = sh
        .find("run python3 scripts/gen_inspect_snapshots.py")
        .expect("make-fixtures runs the inspect snapshot generator");
    assert!(images < snapshots, "snapshots come after the images");
    assert!(
        sh.contains("--keelsign)"),
        "make-fixtures takes --keelsign PATH"
    );
    assert!(sh.contains("${keelsign[@]+\"${keelsign[@]}\"}"));
    let script = read("scripts/gen_inspect_snapshots.py");
    for needle in [
        "keelsign/tests/snapshots/inspect",
        "--check",
        "--keelsign",
        "\"cargo\", \"run\", \"-q\", \"-p\", \"keelsign\", \"--locked\"",
    ] {
        assert!(
            script.contains(needle),
            "scripts/gen_inspect_snapshots.py lacks `{needle}`"
        );
    }
}

/// SHA-53 AC4 / TP4: the `ci` job builds the release binary and runs the README quickstart
/// through scripts/check-quickstart.sh, which runs the `## Quickstart` block within 300 s.
#[test]
fn ci_runs_the_readme_quickstart_shell_test() {
    let ci = read(".github/workflows/ci.yml");
    let host = ci_job(&ci, "ci");
    for needle in [
        "- name: readme quickstart (shell test)",
        "cargo build --release -p keelsign --locked\n",
        "scripts/check-quickstart.sh --keelsign target/release\n",
    ] {
        assert!(host.contains(needle), "ci job must have `{needle}`");
    }
    let build = host
        .find("cargo build --release -p keelsign --locked")
        .expect("release build");
    let run = host
        .find("scripts/check-quickstart.sh --keelsign")
        .expect("script");
    assert!(build < run, "the release build comes first");

    let script = read("scripts/check-quickstart.sh");
    for needle in [
        "set -euo pipefail",
        "## Quickstart",
        "bash -euo pipefail -c \"$block\"",
        "SECONDS",
        "budget=300",
        "--keelsign",
    ] {
        assert!(
            script.contains(needle),
            "scripts/check-quickstart.sh lacks `{needle}`"
        );
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let mode = fs::metadata(workspace_root().join("scripts/check-quickstart.sh"))
            .expect("stat")
            .permissions()
            .mode();
        assert_ne!(mode & 0o111, 0, "scripts/check-quickstart.sh is executable");
    }
}

/// SHA-53 AC4: the README quickstart is one `sh` block that builds nothing itself and runs
/// every keelsign command (keygen, pubkey, sign, verify, inspect), with the install line
/// before it.
#[test]
fn readme_quickstart_block_names_every_command() {
    let readme = read("README.md");
    let section = readme
        .split("\n## Quickstart\n")
        .nth(1)
        .and_then(|rest| rest.split("\n## ").next())
        .expect("README.md has a `## Quickstart` section");
    assert!(section.contains("cargo install --path keelsign --locked"));
    assert_eq!(section.matches("```sh\n").count(), 1, "one sh block");
    let block = section
        .split("```sh\n")
        .nth(1)
        .and_then(|rest| rest.split("\n```").next())
        .expect("sh block");
    let commands: Vec<&str> = block
        .lines()
        .filter_map(|line| line.strip_prefix("keelsign "))
        .filter_map(|rest| rest.split_whitespace().next())
        .collect();
    assert_eq!(commands, ["keygen", "pubkey", "sign", "verify", "inspect"]);
    assert!(
        !block.contains("cargo "),
        "the block uses the installed binary"
    );
    assert!(block.contains("tests/fixtures/images/mcuboot-ed25519.bin"));
    // SHA-67: the quickstart signs with a stateful LMS/HSS key, after a warning that links
    // the rules for such keys.
    assert!(block.contains("keelsign keygen --alg lms-sha256-m32-h10 "));
    assert!(block.contains("signing.pem.state"));
    let before = section.split("```sh\n").next().unwrap_or_default();
    assert!(
        before.contains("stateful") && before.contains("docs/keys.md#stateful-lms-keys"),
        "the quickstart warns that LMS/HSS keys are stateful before the block"
    );
}

/// SHA-67 TP3 on target (NEEDS-HARDWARE): docs/signing.md documents the manual procedure
/// that verifies keelsign-signed LMS images on the boards, and the pieces it uses exist:
/// the host test that keeps the images, scripts/lms_image_kat.py (standard library only)
/// and lms-kat's `KEELSIGN_LMS_TARGET` override.
#[test]
fn lms_on_target_procedure_is_documented() {
    let signing = read("docs/signing.md");
    let section = signing
        .split("\n## On-target check\n")
        .nth(1)
        .and_then(|rest| rest.split("\n## ").next())
        .expect("docs/signing.md has an `## On-target check` section");
    const HOST_TEST: &str =
        "images_at_leaves_0_1_and_1023_verify_with_keelsign_verify_and_cnsa_2_0";
    for needle in [
        "NEEDS-HARDWARE",
        HOST_TEST,
        "--nocapture",
        "scripts/lms_image_kat.py --pub lms.pub.pem --out /tmp/lms-leaves.bin leaf-0.bin leaf-1.bin leaf-1023.bin",
        "KEELSIGN_LMS_TARGET=/tmp/lms-leaves.bin cargo test --release --locked --test lms -- lms_kat",
        "passed=3/3",
        "rotation: skipped (override fixture has no rotation cases)",
        "LMS_KAT_TARGET_OVERRIDDEN",
        "benches/nrf52840-mldsa",
        "benches/rp2350-mldsa",
    ] {
        assert!(
            section.contains(needle),
            "docs/signing.md `## On-target check` lacks `{needle}`"
        );
    }
    let test = read("keelsign/tests/lms_sign.rs");
    assert!(test.contains(&format!("fn {HOST_TEST}()")));
    assert!(test.contains("scripts/lms_image_kat.py") && test.contains("lms_kat::run_fixture"));

    let script = read("scripts/lms_image_kat.py");
    for line in script
        .lines()
        .filter(|l| l.starts_with("import ") || l.starts_with("from "))
    {
        let module = line.split_whitespace().nth(1).unwrap_or_default();
        assert!(
            ["argparse", "base64", "hashlib", "struct", "sys", "pathlib"].contains(&module),
            "scripts/lms_image_kat.py imports `{module}`: standard library only"
        );
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        let mode = fs::metadata(workspace_root().join("scripts/lms_image_kat.py"))
            .expect("stat")
            .permissions()
            .mode();
        assert_ne!(mode & 0o111, 0, "scripts/lms_image_kat.py is executable");
    }

    let build = read("benches/lms-kat/build.rs");
    for needle in [
        "KEELSIGN_LMS_TARGET",
        "cargo:rerun-if-env-changed=KEELSIGN_LMS_TARGET",
        "is_absolute",
        "LMS_KAT_TARGET_FIXTURE",
        "LMS_KAT_TARGET_CASES",
        "LMS_KAT_TARGET_OVERRIDDEN",
    ] {
        assert!(
            build.contains(needle),
            "benches/lms-kat/build.rs lacks `{needle}`"
        );
    }
    let lib = read("benches/lms-kat/src/lib.rs");
    assert!(lib.contains("include_bytes!(env!(\"LMS_KAT_TARGET_FIXTURE\"))"));
    assert!(lib.contains("env!(\"LMS_KAT_TARGET_CASES\")"));
    assert!(lib.contains("env!(\"LMS_KAT_TARGET_OVERRIDDEN\")"));
}
